### ISSUE TITLE
Dlib training for kids database

### ISSUE THREAD

**Issue by mschaudhari** [davisking/dlib#1032]
I'm trying to train an Face detector using Dlib. I selected close to 1000 images for training. As per the documentation, i have created `training_with_face_landmarks.xml`  using that images. But, i don't understand, 

- What are the images used for `testing_with_face_landmarks.xml` file?
- Both `training_with_face_landmarks.xml` and `testing_with_face_landmarks.xml` files use same images?

Thanks in advance.

**Comment by davisking** [comment]
No, the point is to see how good your detector really does.  To test it.  To see if it really works.  You can't test it on images it was trained on because it might have just memorized the particular faces in those images.  **This is true of any machine learning algorithm, you always need to test the results to see if it really worked**.
