### ISSUE TITLE
[suggestion] deserialize of compressed files

### ISSUE THREAD

**Issue by andriy-gerasika** [davisking/dlib#1047]
Hello,
what do you think about incorporating (idea) of https://github.com/geromueller/zstream-cpp into dlib? Basically it is a wrapper around iostream and zlib, so you can deserialize .dat files like:
```
            if (url.endsWith('z') || url.endsWith('Z')) {
                ifstream stream(url.toStdString(), ios::in | ios::binary);
                zstream::igzstream zstream(stream);
                deserialize(result, zstream);
            } else
                deserialize(url.toStdString()) >> result;

```
I mean, dlib already includes zlib inside external folder, so if you recompress dlib model files with gz compression instead of bz2, it would be possible to read these files directly by dlib, without manual decompression step
p.s.
I also have code for iostream wrapper around bzip2 lib, so direct reading of .dat.bz2 from c++ code is possible, if you are willing to incorporate bzip2 lib into dlib/external...

**Comment by davisking** [comment]
I don't really want to do this since I have a hard time seeing who it helps.  The people who are already confused about the need to decompress files are just going to be even more confused with additional dependencies.  There will be people posting problems like: "I don't want to use cmake, so I compile the .cpp files myself (but I don't know what linking is so I didn't link to zlib), but now I can't open the model file even though the example says it should work!".  

That's not to say that decompressing streams aren't nice.  They are, but I don't want to do this with the goal to somehow hide file compression from people who don't know what file compression is.  A better approach is to help them learn that file compression exists and how to decompress files.

I also don't like adding things to dlib/external.  That is sort of an abomination.  I only did it because I was inundated with questions like "The instructions say 'link to libpng', what does **link** mean?".

**Comment by andriy-gerasika** [comment]
ok, thanks

**Comment by davisking** [comment]
I guess I'm a little bit torn on this.  It seems nice, but I'm old and crotchety now from all the silly user complaints I get :/

**Comment by andriy-gerasika** [comment]
yeah, that's a burden of popularity :)

in case you'll change mind, here is iostream/bzip2 wrapper code from my project:
http://www.gerixsoft.com/tmp/iostream_bz.h
http://www.gerixsoft.com/tmp/iostream_bz.cpp

**Comment by davisking** [comment]
Yeah, there are worse problems :)

Thanks for the code.  I'll think about it.
