### ISSUE TITLE
Failed to use float datatype in find_min Optimization

### ISSUE THREAD

**Issue by yuyi1005** [davisking/dlib#1077]
Hello,

I want to use l-bfgs with dlib. The datatype of my cost function is float, and the program crashes when I call the find_min function.

Then, I try the example provided in source code, and it works well, but if I change the datatype from "double" to "float" (just replace the "double" in examples/optimization_ex.cpp), it crashes.

The find_min function uses template datatype, and I think it should support both float and double. I read the code and find that some of the values are directly defined using "double", not the template type T, and I try to fix this problem but failed.

Is float datatype supported in Optimization function of dlib? 

version 19.7, windows10, x64, vs2015

**Comment by davisking** [comment]
It crashes?  Do you mean, it doesn't compile?

Fill out the issue template.

**Comment by yuyi1005** [comment]
Sorry I forgot the detail. The crash happened when I tried to fix this problem. It doesn't compile if I just replace the "double". I try to use Template instead of "double" but it seems there are too much double, and involves a lot of files.

**Comment by davisking** [comment]
Right, it shouldn't compile.  The code could be more general but I haven't made it so because there is really no reason to use anything other than double inside the solvers.  Using float will only degrade the solver accuracy.  I won't make it run faster.  In fact, it might run even slower.  So you should let it run in double precision.
