### ISSUE TITLE
Example of semi-supervised learning from image data

### ISSUE THREAD

**Issue by reunanen** [davisking/dlib#1162]
I am often in a situation where I have lots of unlabeled images from a particular (typically very narrow) domain, but only few labeled images.

Instead of coming up with ad hoc solutions case-by-case, I'd like to have a baseline example in dlib that works well and gives good results for some well-known problem. For example, train with the full ImageNet data, but only 1% or 10% of the labels. Or similar for the PASCAL VOC 2012 data (as in #943). Then this baseline can be improved later on, when new papers are published.

So conceptually similar to [`linear_manifold_regularizer_ex.cpp`](http://dlib.net/linear_manifold_regularizer_ex.cpp.html), but for deep learning from image data.

I'm willing to contribute, but I'm not sure which good-enough method would be easiest to implement in dlib. Any suggestions would be appreciated (some recent examples are mentioned [here](https://thecuriousaicompany.com/mean-teacher/)). Also, I really just want to have a solution, so if someone else contributes this, then from my point of view that's even better. :)

---

And yes, I did read this:
> **The issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

But I suppose it's still ok to open up a discussion like this? If not, then I'll just close the issue.

**Comment by davisking** [comment]
I don't really have a sense for what algorithms might work here. So far, my experience has always been that it's better to spend time manually labeling data than to grind on a semi-supervised algorithm. I should qualify that by saying that I do find it to be very useful to train a model on a small dataset, then to use that model to label my unlabled data. Then I retrain the model on the whole dataset and look at the training instances where the new model disagrees with the labels.  Then I adjust the labels and repeat the train and then manual review process a few times.

For instance, if you are making a dog/not-dog classifier you can take all the images that are now labeled as dog and sort them based on the model output so that things predicted to be not-dog come first.  Generally there will be a lot of obvious labeling mistakes there and the sorting makes it really easy to flip their labels.

This "relabel, retrain, predict, find outliers, repeat" loop is something I've done a lot and it's very hard to beat.  For instance, the face recognition model I posted is trained on about 3 million faces. I personally labeled most of the images in this dataset using the above procedure. I forget how much time I ended up spending on the data curation, maybe 40 hours? That's not that much time in the grand scheme of things. Face recognition is relatively tedious because there are so many identities.  But for binary classification it's super easy to label datasets of hundreds of thousands of images this way and end up with a dataset containing very high quality labels. Like if you were at work and you had to really make it work, spending a week grinding on dataset improvement is generally a much better use of time than spending months tweaking algorithms.  Most people vastly underestimate the importance of data curation.

Anyway, that isn't to say semi-supervised learning isn't important.  At the end of the day I hate labeling data. And obviously humans are able to do amazing semi-supervised learning. So we know it's possible and an algorithm that can really do it would be amazing and super useful.  But the bar is quite high since the baseline procedure I suggested above is very effective.  I've never seen an algorithm that can complete with it.  Although that link you sent is saying there have been some great improvements this year. I haven't read those papers yet so maybe this is the year we finally have good semi-supervised algorithms :)

I'm also totally cool with adding reference implementations of published semi-supervised algorithms even if they aren't ultimately superior to the manual review process. So if anyone wants to submit a PR with one that's awesome.

Also, that note in this issue template is not directed at you or questions like this.  It's for people who obviously don't know how to program and are trying to use the issue tracker as a free code writing service. I get a lot of questions that can basically be rephrased as "I have no idea how to program, can you tell me what keys to press to make a program that does X? Where X is some trivial modification to one of the example programs."  Like "how do I save the detected faces to a file?" or some such question.

**Comment by edubois** [comment]
An idea I just have when I read this problem + the provided link, It would be interesting to train a spatial transformer to generate transforms that would improve your recognition. Limited approach for sure, but I think that maybe this could give you enough examples to feed a GAN training, which would extend your training set even more.
