### ISSUE TITLE
[python] unable to import dlib in Travis

### ISSUE THREAD

**Issue by AbdealiJK** [davisking/dlib#120]
Hi,

I installed dlib successfully in my local computer using `pip install dlib`. But when I try to do the same in Travis, it seems to not work.

The `pip install dlib` command reports that it worked fine and says it got successfully installed. But when importing dlib it gives:

```
$ python -c "import dlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: dynamic module does not define init function (PyInit_dlib)
```
Note: `import dlib` works fine in a virtualenv in my laptop.

You could see the full build log where I noticed this at https://s3.amazonaws.com/archive.travis-ci.org/jobs/132168239/log.txt

**Comment by davisking** [comment]
This is almost certainly because it is compiled against the wrong version
of python or boost.python.  You have to make sure you compile against the
same versions of these things as you use when you run it.

**Comment by AbdealiJK** [comment]
That's interesting, so Im fairly sure the python version is the same, as
there is a virtualenv and so on.

Regarding the boost.python - I am installing `libboost-all-dev` in ubuntu
which includes the `libboost-python-dev` package. I guess the python
version in libboost-python-dev would be of the system python (2.7.6 and
3.3.4) whereas the python version in the virtualenv is different (3.5, 3.3,
etc).

Would that possibly cause the issue ? If so, it seems I need to find a way
to install boost.python into the virtualenv

**Comment by davisking** [comment]
That's definitely the issue.  Your python modules have to be compiled
against the version of python you are using.

**Comment by AbdealiJK** [comment]
Thanks for the help, I confirmed this - The travis build with python2.7 imports dlib fine but no other python version can import dlib. This is because the boost.python is only for python2.7

Closing this issue as it's not a fault in dlib.

**Comment by adimittal** [comment]
I figured out the solution, the wrong version of python installation is not the issue.  Calling it with an inconsistent name is.  I have both python2 and python3 so I alias python as python3.  But I checked and checked, boost, boost-python, python everything were using python3.5.0

I even reinstalled like this repeatedly to ensure version:
brew reinstall boost --with-python3 --without-python
brew reinstall boost-python --with-python3 --without-python

Do:
python3 ./face_landmark_detection.py (instead of just ./face_landmark_detection.py because boost needs names to matchup if getting error like 

$ ./face_landmark_detection.py 
Traceback (most recent call last):
  File "./face_landmark_detection.py", line 47, in <module>
    import dlib
ImportError: dynamic module does not define init function (initdlib)
