### ISSUE TITLE
Global function search relative noise magnitude vs variance

### ISSUE THREAD

**Issue by tsoernes** [davisking/dlib#1200]
Are there any heuristics/tips for setting the relative noise magnitude for the upper bounding part of global function search if the variance of the function is known to high-precision?

**Comment by davisking** [comment]
Not really.  You shouldn't have to mess with that parameter though. In all
my testing I found it was very insensitive to its specific value.

**Comment by tsoernes** [comment]
I have a follow up question. Does the scale of relative noise magnitude depend upon the scale of the loss/result, like solver-epsilon does? And furthermore, do you think there exists problems where running N simulations with the same parameters and reporting the average to dlib is better than letting dlib handle it? I have a highly stochastic problem, with stddev 0.003 where a mean difference of 0.01 separated very good from okay parameters. Global function search have worked a bit better than TPE (hyperopt), though hand tuning still seems the better approach, if you have the time ..

**Comment by davisking** [comment]
The scales should not matter.  I included normalization code in there specifically to try and make it scale invariant in this way.  

I'm not really sure about the other stuff.  Maybe.  For instance, if the cost of simulation was very low then sure, it could be a good idea.  Especially if you are telling me that you don't want to get "bad" solutions that are just accidentally good because of noise. The code in dlib is going to find you the single best point its seen, which for a highly noisy problem is going to be one of the lucky points that got a lot of positive noise added to it.  If that's a bad outcome then you need to do something to filter the noise.
