### ISSUE TITLE
anet_type net for android

### ISSUE THREAD

**Issue by NetoDevel** [davisking/dlib#1238]
I'm implementing facial recognition on android and it works great, but I'm taking a considerable time to convert a single photo into
std :: vector <matrix <float, 0,1 >> face_descriptors = net (faces).
(this array of faces in my scenario will always only have one element).

This "conversion" calling the net (faces) method takes 4 seconds which is not feasible for my application, is there any way to optimize this time for android?

```

using anet_type = loss_metric <fc_no_bias <128, avg_pool_everything <
         alevel0 <
                 alevel1 <
                         alevel2 <
                                 alevel3 <
                                         alevel4 <
                                                 max_pool <3,3,2,2, relu <affine <with <32,7,7,2,2,
                                                         input_rgb_image_sized <150>
                                                 >>>>>>>>>>>>;

anet_type net;
```

Congratulations on the project :)

**Comment by davisking** [comment]
Make sure you link to an optimized BLAS library.

**Comment by NetoDevel** [comment]
Thanks for the answer.

I've been in dlib / config.h and enabled #define DLIB_USE_BLAS.

**Now I'm having this error exit:**
```
Error: (220) undefined reference to 'cblas_dgemm'
Error: (220) undefined reference to 'cblas_dgemm'
Error: (150) undefined reference to 'cblas_saxpy'
```
Sorry for the question, but is it only necessary to enable this in config.h to use blas?

**Comment by ANZDB** [comment]
@NetoDevel : Congratulations for using DLIB to Android. I am trying to do the same thing. However i get error as "Error:error: undefined reference to 'dlib::cpu::pooling::pooling()" whenever i use 'anet_type net' in my jni module. Can you please tell where to declare and defined the anet_type in Android project?

**Comment by NetoDevel** [comment]
@ANZDB
exactly like this example:
https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp

**Comment by ANZDB** [comment]
@NetoDevel: Thanks for replying. I resolved this issue by Adding Source.cpp in Android.mk file for generating the DLIB static library. But now i am getting crash issue on Load library call. Have you added DLIB as static library? or as something else?

**Comment by NetoDevel** [comment]
I added with CMAKE.
Download the dlib and put it in the libs folders and then set the cmake

```
cmake_minimum_required(VERSION 3.4.1)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fexceptions -std=c++11")

add_subdirectory(../../../libs/dlib dlib_build)
add_library(kotlin-jni SHARED
            kotlin-jni.cpp
            jni_fileutils.cpp
            recognition.cpp)

# Include libraries needed for kotlin-jni lib
target_link_libraries(kotlin-jni
            android
           -ljnigraphics
            log
            dlib::dlib)

```

**Comment by ANZDB** [comment]
@NetoDevel:Thanks a ton for your response .Now i will try with CMake. Actually i was trying with NDK.  Do u have any idea if Face recognition can work with NDK setup in Android?

**Comment by NetoDevel** [comment]
It works yes I did it here, but it's like I mentioned when I opened the issue ta very slow for my scenario, and I'm still trying to add openblas to android and dlib .. it's not being easy ..

**Comment by ANZDB** [comment]
@NetoDevel:True. I am finding it difficult at every step. :(

**Comment by NetoDevel** [comment]
@davisking 
I managed to put openblas on an android project, but dlib does not recognize openblas...

**Comment by ANZDB** [comment]
@NetoDevel : Did you use the OpenBlas provided inside /dlib/external/cblas or https://www.openblas.net/ ?

**Comment by ANZDB** [comment]
@davisking : Even i am facing the same errors as mentioned by @NetoDevel related to BLAS library in Android. I am using the CBLAS provided inside /dlib/external/cblas. I followed all the steps provided in readme file and CMake file. But the Android.mk is not able to find the definitions of saxpy_ , dgemm_ etc. As written in the README file inside the CBLAS, is there any way to Compile and Build CBLAS (just the part important for DLIB). How to do that using the cblas provided in the DLIB package?  I am trying to avoid the Complex way of doing it i.e . https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android ?(I do not want the entire BLAS library as of now.)

Any pointers will be appreciated.Please help.Thanks in advance.

**Comment by davisking** [comment]
dlib/external/cblas has nothing to do with openblas and is not appropriate for you to use here. Don't use it.  It doesn't contain a blas library. That's not what cblas is. **cblas is not blas**. Just ignore it.

You need to install or compile openblas or some other blas library and use that.  I don't use android so I don't know what you do to install a blas on android. But it's not dlib specific.  You guys should google how to install openblas on android.

**Comment by ANZDB** [comment]
@davisking:Thanks a ton for clearing my misconception. Now i will concentrate on Just BLAS.

**Comment by NetoDevel** [comment]
We managed to make the dlib recognize openblas when compiled in android with JNI, you should compile openblas on your host machine
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android, and inside the folder it will create you should access this file: `/home/openblas-install/OpenBLAS/OpenBLAS /lib/cmake/openblas/OpenBLASConfig.cmake `and `add SET (OpenBLAS_LIBRARIES /home/openblas-install/OpenBLAS/OpenBLAS/lib/libopenblas.a)`.
 
and ready it will recognize the openblas, remembering that it needs to compile a .a for various types of processors.

It greatly improved the perfomance of dlib on android, Thanks to all.

**Comment by sergiogut1805** [comment]
Hi @NetoDevel,


I am working on DLib android project, i build with cmake, the project works, but the performance is bad, i am trying many ways to link OpenBlas compiled for ARM7 to Dlib on android studio, but not link never!! 😞


Dlib not detect OpenBlas for android.


 *****************************************************************************
 *** No BLAS library found so using dlib's built in BLAS.  However, if you ***
 *** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
 *** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
 ***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
 *** Or you can easily install OpenBLAS from source by downloading the     ***
 *** source tar file from http://www.openblas.net, extracting it, and      ***
 *** running:                                                              ***
 ***    make; sudo make install                                            ***
 *****************************************************************************

i do:


https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android


and use the compiled versión after install, also i do:


your answer:

We managed to make the dlib recognize openblas when compiled in android with JNI, you should compile openblas on your host machine
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android, and inside the folder it will create you should access this file: /home/openblas-install/OpenBLAS/OpenBLAS /lib/cmake/openblas/OpenBLASConfig.cmakeand add SET (OpenBLAS_LIBRARIES /home/openblas-install/OpenBLAS/OpenBLAS/lib/libopenblas.a).

and ready it will recognize the openblas, remembering that it needs to compile a .a for various types of processors.

It greatly improved the perfomance of dlib on android, Thanks to all.




But Dlib not detects OpenBlas...


I build ARM7 openblas and the abi in the android is the same, i should build all procesors(

"x86", "x86_64", "armeabi", "armeabi-v7a", "arm64-v8a") for that dlib detect openblas?? 
Please help me i am trying many things!! and OpenBlas never is detected 😞

Please share with me your android project and OpenBlas compiled libs for testing and implement the diferences on my setup.

I send you my android project with dlib 19.10 compiled to  josevieira.dev@gmail.com.
and the comands to build standalone and OpenBlas for ARM:

Standalone:
export NDK=/home/dl-sergio/Android/Sdk/ndk-bundle

$NDK/build/tools/make-standalone-toolchain.sh --arch=arm --platform=android-21 --install-dir=/tmp/my-android-toolchain --toolchain=arm-linux-android-clang3.6 --force


after i copy my-android-toolchain to NDK toolchains folder and use them.
OpenBlas for ARM:
export NDK_BUNDLE_DIR=/home/dl-sergio/Android/Sdk/ndk-bundle

# Set the PATH to contain paths to clang and arm-linux-androideabi-* utilities
export PATH=${NDK_BUNDLE_DIR}/toolchains/my-android-toolchain/bin:${NDK_BUNDLE_DIR}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

# Set LDFLAGS so that the linker finds the appropriate libgcc
export LDFLAGS="-L${NDK_BUNDLE_DIR}/toolchains/my-android-toolchain/lib/gcc/arm-linux-androideabi/4.9.x"

# Set the clang cross compile flags
export CLANG_FLAGS="-target arm-linux-androideabi -marm -mfpu=vfp -mfloat-abi=softfp -gcc-toolchain ${NDK_BUNDLE_DIR}/toolchains/amy-android-toolchain/"

#OpenBLAS Compile
make TARGET=ARMV7 ONLY_CBLAS=1 AR=ar CC="clang ${CLANG_FLAGS}" HOSTCC=gcc ARM_SOFTFP_ABI=1 -j4

sudo make install or 

i use the standalone toolchain and then build openblas wit this??
also i use NDK 17, OpenBlas  0.2.20 and ubuntu 17.04

i also modify OpenBLASConfig.cmake with SET(OpenBLAS_LIBRARIES /home/opt/OpenBLAS/lib/libopenblas.a)

Please help me... i point to correct path but i think that OpenBlas is bad generated(succesfull but i do something wrong in the proccess) 
the headers are wrong or something doing that dlib/cmake not detect the libraries.

y wait for your answer....I will donate/pay if necessary.

Best regards.

**Comment by NetoDevel** [comment]
@sergiogut1805,
All the challenge to linking the openblas  were given in this issue, I can not provide you with a complete example for such a problem, please read the issue carefully.

try using NDK 14 for the autonomous toolchain.

**Comment by backylee** [comment]
@sergiogut1805  did u build android app with openblas ? if u did it, pls show me how, i met the same issue.   thanks a lot

**Comment by ImJongHyuk** [comment]
> We managed to make the dlib recognize openblas when compiled in android with JNI, you should compile openblas on your host machine
> https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android, and inside the folder it will create you should access this file: `/home/openblas-install/OpenBLAS/OpenBLAS /lib/cmake/openblas/OpenBLASConfig.cmake `and add `SET (OpenBLAS_LIBRARIES /home/openblas-install/OpenBLAS/OpenBLAS/lib/libopenblas.a)`.
> 
> and ready it will recognize the openblas, remembering that it needs to compile a .a for various types of processors.
> 
> It greatly improved the perfomance of dlib on android, Thanks to all.

NetoDevel, thanks a million!!!!!
Your efforts have helped me greatly!!!

**Comment by deamonDevs** [comment]
@NetoDevel I have done all the steps mentioned in [https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android](url), I have successfully installed OpenBLAS but don't Dlib is using it or not. 
         But, I am getting same results after compiling JNI's with OpenBLAS and without OpenBLAS

**Comment by KMKnation** [comment]
> We managed to make the dlib recognize openblas when compiled in android with JNI, you should compile openblas on your host machine
> https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android, and inside the folder it will create you should access this file: `/home/openblas-install/OpenBLAS/OpenBLAS /lib/cmake/openblas/OpenBLASConfig.cmake `and add `SET (OpenBLAS_LIBRARIES /home/openblas-install/OpenBLAS/OpenBLAS/lib/libopenblas.a)`.
> 
> and ready it will recognize the openblas, remembering that it needs to compile a .a for various types of processors.
> 
> It greatly improved the perfomance of dlib on android, Thanks to all.

Hello @NetoDevel , 

I compiled the openblas for every processor but now confused in where to put 
SET (OpenBLAS_LIBRARIES /home/openblas-install/OpenBLAS/OpenBLAS/lib/libopenblas.a)

Can you please help me in this ?

**Comment by KMKnation** [comment]
Finally compiled dlib library with the openblas :smile: 

@NetoDevel is right 

> @sergiogut1805,
> All the challenge to linking the openblas were given in this issue, I can not provide you with a complete example for such a problem, please read the issue carefully.
> 
> try using NDK 14 for the autonomous toolchain.

**Comment by Mik-el** [comment]
Hi @netodevel 

I resulted to compiled OpenBlas for Android! (the script from the Readme repo didn't work for me, so I had to fix it)
Reading the compilation log it seems that the default output/installation directory is `/opt/OpenBLAS`.
Indeed `locate libopenblas.so` gives:

```
/home/user/Downloads/OpenBLAS/libopenblas.so
/home/user/Downloads/OpenBLAS/libopenblas.so.0
/opt/OpenBLAS/lib/libopenblas.so
/opt/OpenBLAS/lib/libopenblas.so.0
```

As you suggested in this issue, I edited the `OpenBLASConfig.cmake` adding `SET(OpenBLAS_LIBRARIES /opt/OpenBLAS/lib/libopenblas.a`)  and also `SET(OpenBLAS_LIBRARIES  /opt/OpenBLAS/lib/libopenblas_cortexa57p-r0.3.21.dev.a` ) (even if it's a symlink to the previous one) .

But when I try to compile Dblib (using the script from [this repo](https://github.com/Luca96/dlib-for-android)) it tells me it can't find OpenBlas:

```
*** No BLAS library found so using dlib's built in BLAS.  However, if you ***
*** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
*** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
*** Or you can easily install OpenBLAS from source by downloading the     ***
*** source tar file from http://www.openblas.net/, extracting it, and     ***
*** running:
```

(I installed `libopenblas-dev` and `liblapack-dev` even if I don't need them since I'm doing a cross-compilation and I think they're packages for compiling for the same architecture)

I also tried/resulted to compile OpenBlas into a different directory (in the .sh script I replaced `sudo make install `with `sudo make install DESTDIR=/home/user/Downloads/OpenBlasDestdir`) but OpenBlas does not get recognized by Dlib anyway.
What could be the problem?
