### ISSUE TITLE
is dlib DeepLearning  usable for distracted driver training ? 

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1298]
Hi,

We are working on a project and mainly using the dlib for reading face landmarks and metadata that we can calculate from it.

Can we use further such as distracted driver detection  ? any direction will be appriciated and we have a humble budget for further help (university proj.).

Best

**Comment by davisking** [comment]
Yes, you could certainly do something like this with dlib. You should find
some CVPR papers or something similar that discusses techniques and try out
their ideas.

**Comment by MyraBaba** [comment]
humble question:

I have 10 category  of drivers photos (ie : texting, lookingbehind, usingMobile  etc).

Do you think I have any usefull out come from dnn_metric_learning_on_images_ex.cpp ?

**Comment by MyraBaba** [comment]
bythe way how I cab use 640x480 images in dnn_metric_learning_on_images_ex.cpp  ?  is it only accepting cols = rows images?

best..

**Comment by davisking** [comment]
You change the network definition to something that makes sense for those image sizes.  Although I don't see why the network in that example would fail to execute for images of any random size.  But you didn't say what the problem was so I don't know. 

In any case, as is usually my advice, you need to do experiments and see what works.
