### ISSUE TITLE
CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.

### ISSUE THREAD

**Issue by TzRay** [davisking/dlib#1329]
# Why I can't use the CUDA?
And the tensorflow-gpu runs normally.
> CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.

``` Building extension for Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
Invoking CMake setup: 'cmake D:\Desktop\dlib-19.12\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\Desktop\dlib-19.12\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=D:\Program Files\python\python.exe -DDLIB_USE_CUDA=yes -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=D:\Desktop\dlib-19.12\build\lib.win-amd64-3.6 -A x64'
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.14.26428.1
-- The CXX compiler identification is MSVC 19.14.26428.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: D:/Program Files/python/python.exe (found version "3.6.4")
-- Found PythonLibs: D:/Program Files/python/libs/Python36.lib
-- pybind11 v2.2.2
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling SSE4 instructions
-- Using CMake version: 3.11.1
-- Compiling dlib version: 19.12.0
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found BLAS: D:/ProgramData/Anaconda3/Library/lib/mkl_intel_lp64_dll.lib;D:/ProgramData/Anaconda3/Library/lib/libiomp5md.lib;D:/ProgramData/Anaconda3/Library/lib/mkl_intel_thread_dll.lib;D:/ProgramData/Anaconda3/Library/lib/mkl_core_dll.lib
-- Looking for sgesv
-- Looking for sgesv - found
-- Looking for sgesv_
-- Looking for sgesv_ - found
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.5")
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.
-- *** The output of the failed CUDA test compile is shown below:
-- ***   Change Dir: D:/Desktop/dlib-19.12/build/temp.win-amd64-3.6/Release/dlib_build/cuda_test_build
   ***
   ***   Run Build Command:"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe" "ALL_BUILD.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=15.0" ```

**Comment by davisking** [comment]
Read the rest of that error message. It's going to tell you that the version of Visual Studio you have installed is not supported by NVIDIA's CUDA tooling.  You need to install a compiler that is supported by NVIDIA.  For windows, I recommend visual studio 2015.

**Comment by shab07** [comment]
Hello Sir ,
I was getting the error  with cudnn not found because the CMAKE_PREFIX_PATH was not set properly. I think I set it correct. 
But after that cuda compilation failed::: 

`-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. 
-- *** The output of the failed CUDA test compile is shown below: 
-- ***   Change Dir: /home/kryptoblocks/Documents/abhishek/dlib/build/temp.linux-x86_64-3.7/dlib_build/cuda_test_build
   ***   
   ***   Run Build Command:"/usr/bin/make"
   ***   [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
   ***   /usr/include/c++/5/functional(78): error: class "std::thread" has no member "result_type"
   ***             detected during:
   ***               instantiation of class "std::_Maybe_get_result_type<_Functor, void> [with _Functor=std::thread]" 
   ***   (86): here
   ***               instantiation of class "std::_Weak_result_type_impl<_Functor> [with _Functor=std::thread]" 
   ***   (184): here
   ***               instantiation of class "std::_Weak_result_type<_Functor> [with _Functor=std::thread]" 
   ***   (264): here
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]" 
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]" 
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]" 
   ***   /usr/include/c++/5/future(1638): here
   ***   
   ***   /usr/include/c++/5/functional(266): error: class "std::thread" has no member "argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]" 
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]" 
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]" 
   ***   /usr/include/c++/5/future(1638): here
   ***   
   ***   /usr/include/c++/5/functional(267): error: class "std::thread" has no member "first_argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]" 
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]" 
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]" 
   ***   /usr/include/c++/5/future(1638): here
   ***   
   ***   /usr/include/c++/5/functional(268): error: class "std::thread" has no member "second_argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]" 
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]" 
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]" 
   ***   /usr/include/c++/5/future(1638): here
   ***   
   ***   4 errors detected in the compilation of "/tmp/tmpxft_000060ce_00000000-7_cuda_test.cpp1.ii".
   ***   CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:262 (message):
   ***     Error generating file
   ***     /home/kryptoblocks/Documents/abhishek/dlib/build/temp.linux-x86_64-3.7/dlib_build/cuda_test_build/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o
   ***   
   ***   
   ***   CMakeFiles/cuda_test.dir/build.make:63: recipe for target 'CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o' failed
   ***   make[2]: *** [CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o] Error 1
   ***   CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cuda_test.dir/all' failed
   ***   make[1]: *** [CMakeFiles/cuda_test.dir/all] Error 2
   ***   Makefile:83: recipe for target 'all' failed
   ***   make: *** [all] Error 2
   ***   
-- *****************************************************************************************************************
`
