### ISSUE TITLE
'Install' target for dlib_python

### ISSUE THREAD

**Issue by Kicer86** [davisking/dlib#1369]
## Expected Behavior
I'm building python bindings for dlib (dlib/tools/python) with CMake. The only one thing I'm missing is INSTALL target which would move dlib.cpython lib to a proper location. This is a problem for me as without it I need to use ugly workaround in my project (which uses dlib as a subproject), to locate and install dlib.cpython lib. 

## Current Behavior
No install target.

## Steps to Reproduce

* **Version**: current master (3aad318e)
* **Where did you get dlib**: github
* **Platform**: 64bit Arch Linux
* **Compiler**: gcc

**Comment by davisking** [comment]
You are supposed to use setup.py. Why don’t you want to do that?

**Comment by Kicer86** [comment]
Oh thx. I wasn't aware of this script.

**Comment by Kicer86** [comment]
One more thing: cmake target would be easier to integrate with existing cmake projects. Script still requires some hacks.

**Comment by davisking** [comment]
You are using python right?  Why don’t you want to use python’s package system for python modules?

**Comment by Kicer86** [comment]
I'm using c++ which launches some python scripts. It would be easier for me to build dlib together with my app, but currently it is not easy to do.

**Comment by davisking** [comment]
What do you do about all the other python modules you use. Like numpy?

**Comment by Kicer86** [comment]
Generally speaking I do not have that much problem on linux, where dlib and other python modules are installed on my system. Now I'm trying to get things work on windows where I need to provide everything which my app depends on. At this moment I'm trying to find nice way to install dlib. Other python stuff is in a queue ;)

**Comment by davisking** [comment]
You should really use the python package manager.

**Comment by davisking** [comment]
Anyway, I'm not going to add an install target in cmake.  I used to have one but most people who use python haven't got any idea how to use the dlib.so file if it's not installed by the python package manager into dist-packages.  That is, they don't know what the python path is, or what dist-packages is, or what a .so file is, or any of that stuff.  They just know they type some magic command and then they can write `import dlib` and it works or doesn't.  I still get many confused questions from people who have multiple copies of python installed and they installed dlib in one python's dist-packages but then started using a different python where isn't not installed and they are confused.  Many of them don't seem to even understand what a filesystem is.

So I used to have a cmake install target that would copy the dlib.so file into the python_examples folder because that lets you just run the examples, since python always searches the current folder for modules.  That seems like the simplest possible example to show what's going on.  You got the .py example program and the dlib.so you are loading, *which is what the example is about*.  But like I was saying above, it turns out that most python users can't handle that.  I honestly think many of the people who email me don't understand what a filesystem is. 

Anyway, because of all that there is no way I'm giving python users more than one path to install dlib.  I get enough confused emails already. You have to generally assume that many python users are just learning to use a computer so things need to be as easy and 'this is the one and only path' as possible.

**Comment by Kicer86** [comment]
I see ok, I'll handle it all somehow :)
