### ISSUE TITLE
Is the following method can solve the limit of memory?

### ISSUE THREAD

**Issue by lvmeng8** [davisking/dlib#1370]
Hi, I want to use large images set to retrain face landmark model , but I have not enough ram.  I think if I can use the method of training CNN to train face landmark model. 
In particular, I choice a batch of images from large dataset randomly, and then call the function dlib.train_shape_predictor in while loop. Stop the loop until epoch reach a special number.  I doubt if the method workable. I want to listen to  opinion from you. Thank you.

**Comment by ferrouswheel** [comment]
I'm dealing with a similar issue, so let me share what I've learnt from reading the code:

- The shape predictor uses a forest of regression trees ([paper here](http://www.csc.kth.se/~vahidk/face_ert.html)), so if you specifically want to use a CNN you'll have to figure it out yourself.
- `train_shape_predictor` trains and returns a new shape_predictor object from scratch, so you can't repeatedly call it for each batch/iteration.
- If you can fit all the objects (landmarks and bounding boxes) in memory, then it looks like the image data is only used here: https://github.com/davisking/dlib/blob/master/dlib/image_processing/shape_predictor_trainer.h#L330 - while one could read images as needed in this loop, I need to read more of the code to figure out how memory-bound other parts are when you have a large dataset.

I *think* that because this is a forest of regression trees we should be able to have watch tree created from different partitions of the data?

**Comment by davisking** [comment]
During each iteration the trees are built on the entire dataset.  So that
sort of thing isn't going to work with this algorithm.

The deeper issue is that you shouldn't be running out of ram. A computer
with 32GB of ram ought to be plenty for normal sized datasets.  So unless
your images are just super huge, there shouldn't be an issue.  If they are
super huge downsample them first.  There isn't any reason to use crazily
high resolution images as training data with this algorithm.

**Comment by ferrouswheel** [comment]
Thanks for the clarification Davis.

I'm working with a small filtered subset of Open Images (full dataset is 9 million images). While images with human faces are only part of the overall dataset, this is still 300k images downsampled to have a max dimension of 1024px.

My aim is to create a massive and open set of face annotations that isn't unduly restricted like ibug, using a bootstrapping process from a smaller set of human labelled annotations.

**Comment by davisking** [comment]
Oh, sweet.  That would be pretty awesome.

Still though, just get more RAM.  For instance, if each image were 700x700
pixels and grayscale (the algorithm ignores color, so load images as
grayscale) then you could load over half a million images onto a machine
with 256GB of RAM.  You can just rent a VM on google cloud or AWS with that
to do the training if need be.

**Comment by lvmeng8** [comment]
Thinks for your pretty answer. As ferrouswheel said, we can not solve the problem with loop method. I solve the problem using the computer with 32G ram.
