### ISSUE TITLE
The facial shape predictor fails miserably when the face is rotated a bit too much - improvement proposal 

### ISSUE THREAD

**Issue by Vermeille** [davisking/dlib#1400]
Hi Davis!

As you know, I have been trying to get around this issue by training a new face predictor model, and that did not work. If my understanding is correct, this is a limitation of the algorithm.

1) Anyway, I fixed this with a very small and fast convnet. If you're interested, you can read about it here http://vermeille.fr/dotclear2/index.php/post/39-Face-Recognition-at-scale-%282/N%29 . Dead simple, dead fast, and if you're interested, I can give you the weights (but they're for tf, so I'm not sure if that's of any use to you).

2) Though I'm concerned. To integrate that step in the pipeline you provide, I'm just rotating the face in its bounding box (see what I mean on the blog post). That works wonders but I stumbled upon [those lines](https://github.com/davisking/dlib/blob/0f169ed71f72faaeee9f9e44143553705b3fd4cf/dlib/image_transforms/interpolation.h#L2071) and I'm wondering if I have to actually make the area I'm rotating bigger, because it seems you are increasing the bounding box. If so, I just don't get those equations. What's the logic behind it? Reading the textual description it seems to be something like

```
bb_left -= padding * bb_width;
bb_right += padding * bb_width;
bb_top -= bb_height * padding;
bb_bottom += bb_height * padding
```
 ut your equations seems more sophisticated.

Thanks for your quick replies and your amazing work :)

**Comment by davisking** [comment]
I don't think that's a limitation of the algorithm.  I say this because
I've trained face landmarking models that covered pretty much the full
range of possible poses and they worked just fine.  What you need is a good
training dataset though.  If your training data isn't good then you aren't
going to get a good model.

That code you linked to is just making the face cropping behave the same
way using either the 68 or 5 point models that are publicly available.
There isn't any funny magic there.  You just need to look at the output
image crops and make sure that any other cropping method you use instead
crops faces the same way.  That is, it should output basically the same
cropped image.

**Comment by Vermeille** [comment]
Alright :) I'm intrigued :)

Thanks for your answer! Have a great day :)
