### ISSUE TITLE
how to improve python api

### ISSUE THREAD

**Issue by yyf1986** [davisking/dlib#1401]
detector = dlib.get_frontal_face_detector()
img = io.imread(image)
dets = detector(img,1)

when I run example,that need five seconds,how to improve speed?

**Comment by sid-sundrani** [comment]
Lowering the resolution of the image, if you haven't done that, will speed it up a good amount. If the picture is at 1080p, quarter the width and the height and then run the detector.

**Comment by yyf1986** [comment]
I already do ,but if resize too low,the detector sometimes can not get face.

**Comment by sid-sundrani** [comment]
5 seconds is too much. For me it takes less 0.2s for me and my image resolution is 368 × 656. The face detector with this resolution works well for me. However, because of the lower resolution faces will have to be relatively closer to be detected. 

I wonder how much faster this detector will be if used in c++.
