### ISSUE TITLE
When I use CNN to detect face

### ISSUE THREAD

**Issue by yyf1986** [davisking/dlib#1437]
Ubuntu 16.04
python3.6
dlib 19.15.0
NVIDIA Quadro P4000

```
import dlib
from skimage import io

detector = dlib.get_frontal_face_detector()

img = io.imread("./023_85.jpg")
dets = detector(img, 1)
print(dets)
```
when I use normal way to run, it cost 2 second.

```
import dlib
from skimage import io

detector = dlib.cnn_face_detection_model_v1("./mmod_human_face_detector.dat")

img = io.imread("./023_85.jpg")
dets = detector(img, 1)
print(dets)
```
when I use CNN to run, it cost 2 minutes.command like `CUDA_VISIBLE_DEVICES=0 python3.6 test.py` and I find GPU is not use.
Why I use CNN is slower than normal?

**Comment by yyf1986** [comment]
CUDA 8.0  cuDNN 6.0

**Comment by AlexXandreE** [comment]
Hi, 
not really sure what you are asking but _get_frontal_face_detector()_ is done with HOG classifier which is faster than a neural network without CUDA support.
If your problem is in compiling with CUDA then it's recommended the use of cmake ([](http://dlib.net/compile.html)), i assure you that using the cmake_gui is easy.
Hope this helps.

**Comment by 3073** [comment]
Hi guys 

Could not load image 'mmod_human_face_detector.dat'.
TGA image type not supported

the weight file for cnn face detector of dlib does not work for me....it just pop up syntax error in the line of code which is situated below the weight file
