### ISSUE TITLE
Multiply GPU for  detection aka. face detection

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1482]
Hi Davis,

Thanks again for great library.

I would love to get some suggestions and ideas for multiply GPU usage for face detection.
is this something like this ? : 

EDITED : to NN based 
```
cudaSetDevice(0)
net_type net_0;

cudaSetDevice(1)
net_type net_1;

cudaSetDevice(2)
net_type net_2;


```
4K video stream and 100 fps I need to proces this realtime. I can out multiply nvidia$$$.
have you ever any new benchmark for 2k or 4k frame ?

Best

**Comment by cedriclmenard** [comment]
As far as I know, Dlib does not have proper GPU (CUDA) acceleration for face detection, only face recognition (landmarks), which is faster anyway. This would bring no performance increase.

**Comment by MyraBaba** [comment]
I mistakenly put fhog based one. I meant NN based 

> http://dlib.net/dnn_mmod_face_detection_ex.cpp.html

this one.

How can I increase the speed according to my scenario ?

**Comment by cedriclmenard** [comment]
I am not aware of any "automatic" way to do this (i.e. Dlib doing that for you). Otherwise, according to [this](https://github.com/davisking/dlib/issues/1144), you can use `cudaSetDevice()` or `set_device()`. One of the way you could probably improve performance is by treating each image in parallel :

1. Spawn `n` host threads for `n` devices
2. For each `i` thread, `cudeSetDevice(i)`
3. Each thread consumes 1 image at at time (when it arrives), with a "stride" between images of `n` (for example on 2 devices : image 0 runs on device 0, image 1 runs on device 1, image 2 runs on device 0, image 3 on device 1 and so on)
4. The thread that spawned all the other threads then consume the data.

**Comment by windforce7** [comment]
If you're using dlib as connector of python project and cuda, here's my advice: 
Though a little bit ugly, running one process for each gpu and allocating different parts of the video stream to those processes is a more practical way of doing this. In single-process-single-thread program, tasks running on gpu isn't asynchronous which means your process simply waits for a gpu finishing its business before assigning tasks to another gpu. Therefore there's at most one gpu running at any moment.
Furthermore, I'm not sure if real-time face detection is possible on 4K video streaming.

**Comment by MyraBaba** [comment]
We are using pure c++ due to python performance issue and scale issues.
