### ISSUE TITLE
ImportError: No module named dlib

### ISSUE THREAD

**Issue by Rishav09** [davisking/dlib#1562]
I am trying to install dlib by `python setup.py install` but it is throwing the following error-
`ImportError: No module named dlib` even after getting installed.
Then I tried installing using `pip install dlib`  it is showing dlib is already installed , but even then it is throwing same error on running 

    ./face_recognition.py shape_predictor_5_face_landmarks.dat dlib_face_recognition_resnet_model_v1.dat ../examples/faces
While in terminal on importing dlib ,there is no error coming.
Error coming both on Mac OS X and Ubuntu 16.04

**Comment by marcemira** [comment]
[dlib_fail.log](https://github.com/davisking/dlib/files/2838258/dlib_fail.log)
I am having similar issues just doing `python setup.py install`
I'm on a Ubuntu 19.04 (4.19.0-12-generic), python 3.7
installed all the python dev deps I found.
Now trying to compile by cloning, cmakes builds 100% perfect. but the issue is that python tries the same build but fails... so I left a log if anyone can take a look at please.
Please let me know if

**Comment by medmelek** [comment]
No module named dlib
