### ISSUE TITLE
How to read and learn the dlib source code?

### ISSUE THREAD

**Issue by xueliang** [davisking/dlib#1598]
Hi, davisking,
      I am very interesting in dlib and have used in my research projects for two years. Now I would like to go deeper to the source code. But I find that most functions are defined in header file; and the header files are never included in a cpp file. I wonder how the functions are declared, defined and exported, and what do you compile in the static lib file. Any suggestions on read and learn from the source code? thanks in advance.

**Comment by davisking** [comment]
It's just regular ISO standard C++.  To learn C++, I suggest reading these books: http://dlib.net/books.html

**Comment by facug91** [comment]
In addition to what Davis said, what I can recommend you from my experience, it's to read these three documentations from dlib:  
http://dlib.net/howto_contribute.html  
http://dlib.net/faq.html  
http://dlib.net/intro.html  
They'll give you a very good idea of how the library is structured, and how to get more out of it.  
For example, header files are always included in the cpp files, but not the *_abstract.h, because these last ones are documentation only (as explained in the third link above).
