### ISSUE TITLE
dlib face recognition always recognized

### ISSUE THREAD

**Issue by jenabbhatia** [davisking/dlib#1633]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**:

**Comment by safavakili** [comment]
I recently got the Jetson Nano Dev Kit (https://developer.nvidia.com/embedded/buy/jetson-nano-devkit).

I have tried to run dnn_face_recognition_ex.cpp example from dlib (19.17) on it. It is compiled using CUDA. But the DNN output descriptors are “nan”. I have tested with different JPG files. They are either “nan” or very large numbers (e.g., 2.331234e+15).

I couldn’t figure it out why.

I guess it is because of the GPU. I noticed that you have had such a problem before ( maybe in release 19.1).

I would appreciate if you can help me with that.
