### ISSUE TITLE
Emotion Recognition

### ISSUE THREAD

**Issue by jenabbhatia** [davisking/dlib#1641]
Hello all,
     I want to implement Emotion Recognition from camera like "happy","sad" etc. I need to implement in c++. I want to ask whose performance is better dlib SVM(Support vector machine) or Opencv SVM.

**Comment by davisking** [comment]
What do you mean by performance?

**Comment by jenabbhatia** [comment]
Means which approach takes less recognition time and which method is accurate

**Comment by davisking** [comment]
All SVM implementations are going to be the same here, so long as they are not buggy.  This is because the SVM objective function is convex so any software that trains a SVM should solve it exactly, finding the optimal solution.  If it doesn't it's just buggy.  I haven't used the one in OpenCV, but I would expect that it is fine and works correctly.

With all that in mind, you should use the tool that is most convenient to use.  My experience with OpenCV is that, generally speaking, its documentation is not super great and the APIs are not what I would consider to be modern clean C++.  Although it's not as bad as it used to be.
