### ISSUE TITLE
Expose chinese_whispers to Python

### ISSUE THREAD

**Issue by stalker314314** [davisking/dlib#1642]
Currently, there is http://dlib.net/python/index.html#dlib.chinese_whispers_clustering exposed which takes descriptors and do clustering. If user wants to give it 128D vectors itself (or any other generic edges, for that matter), there is no easy way, as you cannot convert to C++ descriptors from Python. Does it makes sense to either:
* expose `dlib::chinese_whispers` directly from Python API, as `dlib.chinese_whispers(edges: list) -> label list`
* expose `dlib::chinese_whispers` (or overload ``dlib::chinese_whispers_clustering`) to accept list of lists (all elements should have same size), not just list of C++ objects. And C++ would calculate euclidean distance to get edges

Does this sound something that can be accepted in dlib? And with what level of abstraction?

**Comment by davisking** [comment]
Doesn't the existing python API let you pass in arbitrary vectors (e.g. 128D vectors)?  I'm pretty sure that is the case.  

I don't really see how you will be able to meaningfully pass in any kind of edge list type of data structure from python since python is so brutally slow. Any non-trivial graph will take a really long time for python to construct.  I guess for small problems it won't be totally intractable though.  But in any event, I wouldn't reject a PR that added a python API for this method that mirrors the API of the C++ one, that is, one that takes in an edge list.  But I think you will find it hard to make edge lists in python with any reasonable execution speed.

**Comment by stalker314314** [comment]
I didn't found existing API (optimistically sent PR!). If there is some API, feel free to discard this PR.

Yes, it is slow, but considering that alternative is to rewrite edge generation in C++ (or rewrite chinese_whispers in Python:), I think it makes sense to include it). I am struggling with `np.linalg.norm`, so it is not *that* slow (10000s of vertices), others might use some other methods, however - you are right, bottom point is to have option to use this, at all.
