### ISSUE TITLE
Train SVM in python and load in C++

### ISSUE THREAD

**Issue by julian59189** [davisking/dlib#1666]
I have most of my preprocessing in python so I would really love to train the model there and then just load it in C++ and use it. 

I already posted this question on stackoverflow but it might be more suitable [Here.](https://stackoverflow.com/questions/54797915/serialize-dlib-svm-in-python-and-load-in-c)

I there any way to do this? Maybe a workaround?

I really love the fast iteration times in python that allow me to get better results in a short time but of course I don't like python running embedded. I know that dlib is mainly designed for C++ and that I can train it there but I would really prefer using python for training.

**Comment by davisking** [comment]
Most objects exposed through the python API only support saving via pickling, rather than writing out using dlib's normal serialization format.  Although the way they pickle is by using dlib's serializer.  So I'm sure you can dig it out of that, but I've never done that.

I don't think it's actually faster to do this in Python.  I know people talk a lot about prototyping being faster in Python, but as someone who actually knows both languages well I don't believe this is the case.  Things are easy or hard based on what packages are available to help you do the task, the language has little to do with it.  Unless you need to write something high performance, then you can't use Pyhton. 

So if you are proficient in C++ you should just use the C++ API.  Your overall software complexity will be lower if you don't have to do all this between language transfer stuff.  But if you are unfamiliar with C++ and want to use all python you should try and stick to all Python.  Or learn C++.

**Comment by julian59189** [comment]
Thank you for your detailed answer. I will try to dig out the serializer and see if I can use that. 
The data is just a lot more accessible in python than it is in C++ so I prefer it for prototyping. 

But I agree that the language transfer is a huge pain point. That's why I prefer libraries that allow prototyping in Python and using the models in C++. That's also one of the reason why I really like Dlib. Because I can use the functions in python e.g. for data preprocessing for training Tensorflow models and then use the exact same function embedded in C++.

Keep up the great work!

**Comment by VolDonets** [comment]
Sup julian59189!
I have the same problem in my small project. 
Did you achieve any results in your issue?

**Comment by julian59189** [comment]
Hi, sorry I never really figured it out.
I ended up using the sklearn svm and then I used this to export it to c++
https://github.com/nok/sklearn-porter

I hope that helps

**Comment by VolDonets** [comment]
> 
> 
> Hi, sorry I never really figured it out.
> I ended up using the sklearn svm and then I used this to export it to c++
> https://github.com/nok/sklearn-porter
> 
> I hope that helps

Thanks, for help! I hope it will help me=)
