### ISSUE TITLE
[Feature request] Dynamic value for epsilon in MaxLIPO+TR optimiser

### ISSUE THREAD

**Issue by MattWenham** [davisking/dlib#1671]
It would be useful to be able to vary the epsilon value once the MaxLIPO+TR optimiser has started its run.

My example scenario is as follows. I'm using k-fold cross-validation to tune a set of hyperparameters. I've set epsilon to 0.00001, but my cross-validation is returning a typical standard deviation of 0.0002. The optimiser will therefore be _trying too hard_ to refine the optimum value, and I'd like to be able to set epsilon to (say) 0.0001 part-way through the optimisation run.

One way to implement this might be to have a result and a tolerance value returned from the function to be evaluated. If the latter is zero, keep the existing epsilon value in use; otherwise, update it.

**Comment by davisking** [comment]
This is a bit trickier than this, because it's not the case that the solver knows it's within epsilon of the local minima. In general, it could be much farther than that, although in many cases it will be roughly correct.  

Why don't you want to set the epsilon to the higher value the whole time?

**Comment by MattWenham** [comment]
Because you don't know a 'typical' higher value until you've done some sets of cross-validation to get a typical standard deviation. They could be computed beforehand with grid or random search, but that's a bit of a waste of resources.

You could perhaps pass in the results of these 'pre-runs', but I don't know if MaxLIPO+TR would benefit from an arbitrary set of function values for which it hadn't determined the parameters.

**Comment by davisking** [comment]
Using the trust region solver's epsilon isn't a super great way to model objective function noise.  It seems like a better idea to do something like, adding a regularizer/smoothness prior on the quadratic surrogate the TR solver is optimizing.  To say that another way, the TR model fits a local quadratic model to the samples, but if the objective function is noisy you don't want to just find the tightest fitting quadratic model because that will fit to noise and be bad.  You want to find some kind of smoothed model that better approximates the true objective function with noise removed, assuming some kind of smoothness prior is probably sensible.

To do this you need so somehow estimate the noise model.  You also need a good way to fit a quadratic to set of points with a smoothness prior.  One way to do this might be to find the min Frobenius norm model that gets within `epsilon` of all the sampled function points.  Then use that quadratic model in the trust region step.  I think the hard part here is knowing what the noise model/level is.

**Comment by MattWenham** [comment]
Woah, I understand some of that, but since I'm using the Python interface, unless I write my _own_ interface, much of this will be out of scope. I'll bear it in mind for the future though. Thanks.

**Comment by davisking** [comment]
Ha, well, that's what I would do if I wanted to handle noisy objective functions.  The current method doesn't really deal with objective function noise.
