### ISSUE TITLE
GPU advise for 2Mp & 5Mp

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1679]
Hi,

I wan to detect faces from  two camera  👍 
one setup is 2Mp (1920x1200)

second is  5Mp

What would be the required GPU for 20 fps proecess?

1080Ti ?

2080..?

any experience & advise or benchmark?

**Comment by pi-null-mezon** [comment]
Hi, it is not good idea to ask such general question here. In Dlib issues page. But you are lucky, because I am working with face detection. I suggest you to switch to OpenCV, because at a present moment it provides [better detection rate and lower inference time](https://www.learnopencv.com/face-detection-opencv-dlib-and-deep-learning-c-python/) than Dlib CNN face detector. Back to your question, it is not good idea to detect faces on such huge image as 1920x1200. In practice, first you should resize image to something about 200x200 or 300x300 and only then perform face detection by CNN. If you will do so, you can achive 30 fps even on CPU!

**Comment by davisking** [comment]
That’s not what that article says. For instance, it concludes with this: 

> If you can use a GPU, then MMOD face detector [in dlib] is the best option as it is very fast on GPU and also provides detection at various angles.

**Comment by MyraBaba** [comment]
We tested heavily Dlib CNN , MMOD & OpenCV CNN & MTCNN

we are happy with the dlib and mtcnn . OpenCV based caffe and not brought a new improvement.

But it all depends the projects , hardware and specifications.

On the other hand Davis would you mind to share the gpu benchmark if you have any. I have a limited budget (4K usd) and want to buy two gpu. 

Best

BC

**Comment by davisking** [comment]
I don’t have such a benchmark.

**Comment by pi-null-mezon** [comment]
> That’s not what that article says. For instance, it concludes with this: If you can use a GPU, then MMOD face detector [in dlib] is the best option as it is very fast on GPU and also provides detection at various angles.

I am not talking about article's concludes. Article just contains performance measurements, but we see only what we want to see.

**Comment by xsacha** [comment]
I have such benchmarks but it requires a proper chain/flow of detections and recognition, keeping everything in CUDA.
For a single stream at 20 fps you do not even need a GPU. This can be done on CPU.
You can easily do 10 streams on a GTX 1060. The limitation is on video decode engine of your GPU.

**Comment by MyraBaba** [comment]
@xsacha  Thanks for the information . I would love to get more information about the how you did the 10 x 1080p detection at full 25fps speed . Just detection . Recognition handled by other machine. 

We are using opencv to capture h264 / ts stream and feeding the frames . All code in c++

Best

**Comment by xsacha** [comment]
You can do it all on the same machine. For the detection? You can just use OpenCV cuda multiscaledetect. Pick a decently fast Cascade.

The trick is to keep everything on GPU.
