### ISSUE TITLE
Traversing layers

### ISSUE THREAD

**Issue by tomaszgrygiel** [davisking/dlib#1745]
Hi,
I'm working on fine-tuning face recognition model. My goal is to freeze all but first layers of pretrained model.
Basing on some other issues I've approached the problem using `visit_layers` method and implemented visitor as following:
```
class NetVisitor {
public:
    template<typename any_net>

    void operator()(size_t idx, any_net &net) {
    }

    template<typename T, typename U, typename E>

    void operator()(size_t idx, add_layer <T, U, E> &l) {
        if(idx != 0){
            l.layer_details().set_learning_rate_multiplier(0);
        }
    }
};
```
 
Then I called visit method:

```
anet_type net;
    deserialize("dlib_face_recognition_resnet_model_v1.dat") >> net;

    cout << net.num_layers << endl;

    NetVisitor visitor;
    visit_layers(net, visitor);
```

And as a build result I got:

```
error: ‘dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32, 7, 7, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150>, void>, void>::layer_details_type {aka class dlib::affine_}’ has no member named ‘set_learning_rate_multiplier’
```

and many others similar errors. Where's a problem in my approach?

Thanks!

**Comment by davisking** [comment]
Not all layers have `set_learning_rate_multiplier`.  You need to use SFINAE or function overloading or type traits or something to write correct code.  There are a lot of ways to do this kind of thing in C++. You can look at some of the methods in dlib that do this layer traversal if you want some examples.

However, if you want to freeze all the layers but the last you should just precompute all the network outputs for your dataset and save them to disk rather than recomputing them over and over during training.  That would be much faster to train.

**Comment by tomaszgrygiel** [comment]
Got it,
Thanks a lot!
