### ISSUE TITLE
Face detection box influence over recognition (encoding generation)

### ISSUE THREAD

**Issue by ricardovf** [davisking/dlib#1746]
First, thanks for this project, it's really great. 

What want to know if the position of the face box (closer to the center of the face, or further from the face) influences with the generation of the 128 vector encoding generation.

I have 3 possibilities to find the bounding box. Using HOG, using CNN and using a third party API that draws a bigger box, as you can see in our example.

To make the face recognition faster, i would like to use our bounding box detector instead of the HOG or CNN, but i'm not sure if the encoding generation would be different and influence the face recognition (we calculate the distance latter).

If you can't provide the answer, i will run some backtests in our base to find out.

Thanks and keep up the great work!

![detection](https://user-images.githubusercontent.com/453574/56821880-e49bb880-6825-11e9-8567-b6be3b1e5a02.jpg)

Also, i would like to know if your are available for freelance jobs.

**Comment by davisking** [comment]
You need to crop faces the same way the dlib code does it or the face recognition model, the thing that takes in the crop and outputs the 128D vector you mentioned, will not work right.  This is because it's trained on that kind of cropping.  Something else will not work as well.

As an aside, if you look at the code it should be clear that the face landmarking model is really what's responsible for doing the face alignment for cropping.  It doesn't really matter what the box shape is so long as you have a face landmarking model that does the correct alignment.  Here "correct" means the way the one that comes with the dlib face recognition examples does it.  

I don't have any available time to do freelance work right now.

**Comment by ricardovf** [comment]
Thanks for the quick answer.

The models i'm using are the ones from dlib. I'm using the **shape_predictor_5_face_landmarks.dat** to get the landmarks and then the encodings.

Guess i will stick with HOG as i noted that the models were trained using that before going to the landmark extraction.

Thanks one more time!

**Comment by davisking** [comment]
No problem. Note that the 5 point model is trained to work with the boxes from dlib's HOG and CNN face detectors. So you can use either and it will work fine.
