### ISSUE TITLE
Multiclass object detection using pascal VOC not detecting anything

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#1951]
I wanted to try if the DNN object detection, as shown in 
http://dlib.net/dnn_mmod_train_find_cars_ex.cpp.html
works well on a generally available dataset.
So I downloaded the PascalVOC2007 dataset, used imagelab --convert pascal-xml Annotations/*.xml make an imagelab dataset, and ran the example on this dataset, modifying only the batch size from 87 to 24, in order to fit into my 8GB GPU.
To my surprise, the detector did not detect anything, the results reported at the end of the training being 1 0 0.
I even tried to only train a single class detector (for person and for cat, using imagelab to only keep the annotations for these classes), with the same results.
I did not split the dataset in training and testing samples, using the entire dataset for both purposes.
I know that the dataset used to train the dlib example car detector was much more accurately annotated, taking care to not have many aspect ratios, but I still expected do get some detections.
Any idea why this is not working?

**Comment by davisking** [comment]
There are two reasons, first, the CNN in that example is a relatively small CNN compared to the sorts of things people use on bigger things like pascal.  But the much bigger reason is that that dataset is not accurately labeled.  In particular, the loss_mmod layer treats all parts of the image that are not labeled with a box as negative examples.  So it's looking at the data trying to figure out how to make something that makes the fewest mistakes, and it sees all these people or whatever in the background that aren't labeled and it decides the way to make the fewest mistakes is to never detect anything, because otherwise it would "false alarm" on the background objects that aren't labeled, or are labeled inconsistently in terms of box shape.

**Comment by pepeverde9** [comment]
Thank you for the answer.
Sure, I was hoping that there is a way to train dlib multiclass object detection on such a dataset, as starting point for transfer learning, in order to replace the dlib non-dnn object detection with something which trains similarly fast.
But the labeling on this dataset is indeed odd, if only a part of an object is visible, that part is labeled as the (entire) object, but as far as I understand mmod actively suppresses the recogniton of parts of the object as the entire object, so i guess this is the reason why it does not detect anything.
Anyway, dlib is a great library, thank you for creating it.

**Comment by thanhhien1166** [comment]
> --convert pascal-xml Annotations/*.xml

Hi
I ran this line:
!sudo ./imglab -c 000000.xml --convert pascal-xml /Annotations/000000.xml 
When I opened the new 000000.xml file, I received this:
Dummy person
Was there anything wrong with my code?

**Comment by arrufat** [comment]
Try running:
```
./imglab -c pascal.xml --convert pascal-xml /Annotations/*.xml
```
