### ISSUE TITLE
dlib with multiple GPUs

### ISSUE THREAD

**Issue by babylon73** [davisking/dlib#1971]
##  Expected Behavior
Say, I have two GPUs in the system, how to find out which one is used by dlib? I gues it should be specifiable during the build, as a command line argument of the compiled executable or something. IMHO, it is true for both examples and unit tests, especially for unit tests.

## Current Behavior
GPUs (or just one GPU) are utilized by the samples and unit tests, no idea which one, no way to specify one.

## Steps to Reproduce
Just running the samples and unit tests

* **Version**: 19.19
* **Where did you get dlib**: dlib.net
* **Platform**: Win10 x64 10.0.17763
* **Compiler**: MSVC 19.0.24215.1 (VS2015 Update 3)

**Comment by reunanen** [comment]
The basic functionality has been documented [here](https://github.com/davisking/dlib/blob/9d5921406256f1942baf155e2f4ac1e3f2b337e5/dlib/dnn/trainer_abstract.h#L92-L98). So the primary GPU to use can be specified directly using the CUDA API (and not doing anything leads to using a CUDA default, I guess). Additional GPUs, if any, can be passed via the trainer API. Many example programs don't support passing this information from the command line; I guess generally people just [modify the code itself](https://github.com/davisking/dlib/issues/1677#issuecomment-479707436) in order to test different options. I think the examples are meant to be examples, rather than production-ready software.

**Comment by arrufat** [comment]
Usually, this is what I do

``` c++
std::vector<int> gpus(num_gpus);
std::iota(gpus.begin(), gpus.end(), 0);
dlib::sgd solver(0.0001, 0.9); 
auto trainer = dlib::dnn_trainer(net, solver, gpus);
``` 
Where `num_gpus` was passed as a command line argument. Then I control which particular GPUs will be used via `CUDA_VISIBLE_DEVICES`.

```
CUDA_VISIBLE_DEVICES=0,2,3 ./train_ex --num-gpus 3
```
This will make the executable use 3 GPUs (0,2,3).
This way I don't need to rebuild every time I change the GPUs.

**Comment by davisking** [comment]
> I think the examples are meant to be examples, rather than production-ready software.

Yes, this is exactly right. They are documentation.
