### ISSUE TITLE
pybindings dlib to a different environment

### ISSUE THREAD

**Issue by pjardin** [davisking/dlib#198]
hello, this is something I'm struggling with that I hope you can help me with

I'm trying to connect dlib to blender (free and open source 3d software). If I can successfully do that, then I can use your software to control 3d characters on any computer with any webcam in real time. This would be a huge accomplishment. So what I have done so far to try to obtain this goal is when I compile the setup.py it stores dlib my python system packages. From there, I append it to blender's standalone which has its own python and its own boost. In blender I can import dlib, but when I try to use dlib for its complex functions I get this:
```
 predictor = dlib.shape_predictor(predictor_path)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
TypeError: __init__() should return None, not 'NoneType' 
```

but it works fine for 
`detector = dlib.get_frontal_face_detector()`

But on my system all of the dlib functions work fine with no problems. 

talking back and forth on the blender development page, I was able to determine that the most likely problem for this is that the boost dlib is not linking to blenders boost. And some suggest that all I am missing is a pybinding. But I have no idea on what needs to binding. 

So what I'm I doing wrong or what binding I'm i missing? 

using sys.path i gathered all of the python paths and append it to blender

```
pyodbcPath = ['', '/usr/local/lib/python3.5/site-packages/dlib-19.1.0-py3.5-macosx-10.11-x86_64.egg', '/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python35.zip', '/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5', '/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin', '/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload', '/Users/pascaljardin/Library/Python/3.5/lib/python/site-packages', '/usr/local/lib/python3.5/site-packages', '/usr/local/Cellar/numpy/1.11.1/libexec/nose/lib/python3.5/site-packages', '/usr/local/opt/opencv3/lib/python3.5/site-packages']


sys.path.extend(pyodbcPath)
```
but that still does not work

thank you for your time.

**Comment by davisking** [comment]
You need to make sure that you use the same boost in both cases.  That's
the only real solution.  You might get away with using the same version of
boost but really you should link both to the same boost binaries since
otherwise they might have been compiled with different options and
therefore not really be the same boost.  So link with the boost in
blender.  You also need to link with the same version of python as blender
is using.

More generally, when making shared libraries that are going to load into
some application you generally need to use all the same versions of 3rd
party libraries as the hosting application.

**Comment by pjardin** [comment]
cool, gotcha. I think I know what to do now, thank you! :)
