### ISSUE TITLE
Will there be Pre-built binaries that work with python 3.7 and above.

### ISSUE THREAD

**Issue by TahaAnwar** [davisking/dlib#2121]
Currently, the pre-built binaries for dlib only support python 3.6 and below. So meaning if you don't have CMake or a C++ compiler installed then you can still do: 

pip install dlib==19.8.1 

And dlib will be installed without building and compiling, the only condition is that you must be running python 3.6 or below.

So my question when can we expect a binary for python 3.7. 
Thanks.

**Comment by davisking** [comment]
No.  I used to post windows binaries, but I got constant questions about
dlib being slow, not using SIMD instructions, not using CUDA, and things
like that.  This is because prebuilt binaries need to be
lower-common-denominator and so can't use those hardware accelerations.
It's made worse by pip defaulting to binary whl files.  If there is some
way to make this less bad with pip I'm open to suggestions.  But I'm not
open to options that cause `pip install dlib` to always install dlib
without CUDA or SIMD as lots and lots of users will complain.  I also don't
want to distribute cuda binaries, or at least, I personally don't want to
do that as it's a nightmare.  If someone wants to spend time making that a
reality that would be cool.  But they have to commit to keep doing it,
because nvidia's dependencies change several times a year and things need
to be updated to avoid breakage if binary packages are distributed.

**Comment by TahaAnwar** [comment]
Hmm, right that seems to be an issue.

How about this, for every release you release the official version which can be pip installable like right now. But also, you release a binary which can be installed by doing something like **_pip install dlib==19.20.0.b_** just like how some libraries handle the stable and the latest nonstable versions at pypi.

I know that this binary won't be optimized for performance (for reasons you mentioned above) but it would ease the entry barrier for a lot of people who struggle with getting Cmake and a compiler installed properly.

P.S. I don't know if this is going to cost you extra work as I haven't dealt with library maintenance that much so I totally understand if this is not worth the trouble.

**Comment by tstorek** [comment]
Hi,
I know the dlib from the days when I still coded in C++. I loved it for its simplicity and its speed. For python I only tried it ones. However, doesn't "pip install cmake" solve the problem or simply at it in the requirements/setup.py? At least the first dlib-example worked for me. Only the installation takes about 20 min and throws some warnings. 

`(py38) C:\Users\>pip install cmake
Collecting cmake
  Using cached cmake-3.17.3-py3-none-win_amd64.whl (33.7 MB)
Installing collected packages: cmake
Successfully installed cmake-3.17.3

(py38) C:\Users\>pip install dlib
Collecting dlib
  Using cached dlib-19.20.0.tar.gz (3.2 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... |  WARNING: Subprocess output does not appear to be encoded as cp1252
/  WARNING: Subprocess output does not appear to be encoded as cp1252
-  WARNING: Subprocess output does not appear to be encoded as cp1252
|  WARNING: Subprocess output does not appear to be encoded as cp1252
/  WARNING: Subprocess output does not appear to be encoded as cp1252
done
  Created wheel for dlib: filename=dlib-19.20.0-cp38-cp38-win_amd64.whl size=3148374 sha256=4149444d06cce00a5e28a28499876f396127436c68770cf0d53b74c4c2836db5
  Stored in directory: c:\users\tst\appdata\local\pip\cache\wheels\a5\82\2c\2d2ccc604e2c2e35994b89a173d922331f1c6e1af9320a7602
Successfully built dlib
Installing collected packages: dlib
Successfully installed dlib-19.20.0

(py38) C:\Users\>`


I will try some more dlib-examples? why would you need to have the binaries then? I am just curious here.

**Comment by TahaAnwar** [comment]
> Hi,
> I know the dlib from the days when I still coded in C++. I loved it for its simplicity and its speed. For python I only tried it ones. However, doesn't "pip install cmake" solve the problem or simply at it in the requirements/setup.py? At least the first dlib-example worked for me. Only the installation takes about 20 min and throws some warnings.
> 
> `(py38) C:\Users>pip install cmake
> Collecting cmake
> Using cached cmake-3.17.3-py3-none-win_amd64.whl (33.7 MB)
> Installing collected packages: cmake
> Successfully installed cmake-3.17.3
> 
> (py38) C:\Users>pip install dlib
> Collecting dlib
> Using cached dlib-19.20.0.tar.gz (3.2 MB)
> Building wheels for collected packages: dlib
> Building wheel for dlib (setup.py) ... | WARNING: Subprocess output does not appear to be encoded as cp1252
> / WARNING: Subprocess output does not appear to be encoded as cp1252
> 
> * WARNING: Subprocess output does not appear to be encoded as cp1252
>   |  WARNING: Subprocess output does not appear to be encoded as cp1252
>   /  WARNING: Subprocess output does not appear to be encoded as cp1252
>   done
>   Created wheel for dlib: filename=dlib-19.20.0-cp38-cp38-win_amd64.whl size=3148374 sha256=4149444d06cce00a5e28a28499876f396127436c68770cf0d53b74c4c2836db5
>   Stored in directory: c:\users\tst\appdata\local\pip\cache\wheels\a5\82\2c\2d2ccc604e2c2e35994b89a173d922331f1c6e1af9320a7602
>   Successfully built dlib
>   Installing collected packages: dlib
>   Successfully installed dlib-19.20.0
> 
> (py38) C:\Users>`
> 
> I will try some more dlib-examples? why would you need to have the binaries then? I am just curious here.

I can't point out the exact reason but pip install cmake alone doesn't always cut it for many people.

**Comment by davisking** [comment]
Right, the copy of cmake in pip is broken on some platforms.  I don't know
why.  But in any case, it's really easy to download and install cmake from
cmake.org, so I don't really appreciate the issue on windows.  It's a
simple graphical installer, you just need to click install and it just
works.  I think the hangup for people on windows is installing visual
studio and not understanding they need to install the C++ version of visual
studio rather than something like C#.

**Comment by davisking** [comment]
And to make this better I updated the cmake scripts so that users on
windows that haven't installed Visual C++ (the version of visual studio for
C++) will get a very explicit error message telling them to install visual
studio for C++.  The default cmake generated error message is confusing for
people new to windows/C++ development as it talks about other possible
build environments that they have probably never heard of.

**Comment by TahaAnwar** [comment]
Personally I agree with you, Its not much trouble installing visual studio and Cmake from the site, but the newbies in vision with python only background keep complaining about installation, they just want to do pip install and be done with it.

Yes having an explicit CMake error would definitely help, Thank you. :)
