### ISSUE TITLE
cudnn8  cudnnFindConvolutionForwardAlgorithm crashes

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#2175]
Hi, 
i just wanted to load a network (resnet based) which i used for years.

I used cudnn8 + the newest dlib version for the first time.

the whole thing crashes on

                CHECK_CUDNN(cudnnFindConvolutionForwardAlgorithm(
                        context(), 
                        descriptor(data),
                        (const cudnnFilterDescriptor_t)filter_handle,
                        (const cudnnConvolutionDescriptor_t)conv_handle,
                        descriptor(dest_desc),
                        num_possible_algorithms,
                        &num_algorithms,
                        perf_results.data()));

/line 812 cudnn_dlibapi.cpp

in:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudnn_cnn_infer64_8.dll

it says access violation

**Comment by VisionEp1** [comment]
please let me know what further information i can provide to help with resolving this

**Comment by VisionEp1** [comment]
i went back to cuda 10.2 and cudnn 7 everything works as expected

**Comment by davisking** [comment]
That shouldn't happen.  Maybe it's a bug we have to work around in cudnn v8 ¯\_(ツ)_/¯

It's not something I've seen happen yet though.  You will have to debug it.  Like maybe `num_possible_algorithms` is getting set to 0 or something silly, or `cudnnFindConvolutionForwardAlgorithm` is writing outside the bounds of `perf_results`.  Like what happens if you make the `perf_results` vector way bigger? If the error goes away `cudnnFindConvolutionForwardAlgorithm` is probably buggy and writing out of bounds on that array.
