### ISSUE TITLE
CUDA arch sm_50 conflicts with Yocto settings

### ISSUE THREAD

**Issue by nefethael** [davisking/dlib#2297]
Hello,

I'm using Yocto to build a custom distribution for Jetson TX2 board.
Board support is provided by meta-tegra layer that set CUDA nvcc flags `-gpu-architecture=compute_62`, which conflicts with `-arch=sm_50` instructions in dlib CMakeLists files. 

Would it be possible to set arch to sm_50 by default with possibility to override it?

Best regards,
Vincent

Ps: It's not a big issue as I can always patch files in Yocto recipe.

**Comment by davisking** [comment]
It could certainly be set using a cmake variable or option.  If you want to
submit a PR that adds that optionality that would be cool with me.

**Comment by fuzun** [comment]
@davisking 

If there is no benefit of using compute capability 5.0, I think it can be set to sm_30 to support more GPUs.

In my case, I have a rather old GTX 670. It has Kepler architecture but since arch is set to sm_50, I get runtime errors. In fact, I had to spend a lot of time to find what the issue was. Maybe with cmake it is possible to dynamically set correct CUDA arch based on what is available.

Even though Kepler is old, it is supported by CUDA 10 / 11. But GTX 600 series does not have 3.5 compute capability support so CUDA 10 must be used, and for GTX 700 series I think CUDA 11 can be used since it supports 3.5. Good thing is latest cuDNN requires only 3.0 compute capability so maybe it is a better idea to set it to sm_30.

For my case with v19.21, when I override sm_50 to sm_30 and use CUDA 10, dlib works fine with my GTX 670 (even though a little slow :). But I can not see any process in nvidia-smi even though GPU utilization ramps up during execution. If you have any idea on that I'd appreciate if you could tell).

**Comment by davisking** [comment]
I don't know what to tell you unfortunately.  NVIDIA software is frustrating to deal with.  I don't want to be any more in the game of trying to be the all encompassing solution to everyone's possible configurations that I already am.  The current setting of sm_50 is there because sm_30 is now so old it doesn't work for some people.  Maybe CMake could somehow detect the "right" setting but it's not super obvious how that would happen automatically.  I expect any such attempt will result in me getting a flood of emails from people complaining that it's not working right.

**Comment by arrufat** [comment]
I am on the other side of the spectrum, when I build dlib I get warnings saying that:
`nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).`

So I've also been wondering what we can do about it, and I noticed there might be something interesting here:
https://github.com/opencv/opencv/blob/d643a90efa643f10b1426028acaa97aecef54bdf/cmake/OpenCVDetectCUDA.cmake

They seem to have some kind of auto detection for the cuda architectures:
https://github.com/opencv/opencv/blob/d643a90efa643f10b1426028acaa97aecef54bdf/cmake/OpenCVDetectCUDA.cmake#L185-L242

**Comment by davisking** [comment]
This all seems kinda over the top.  A cmake variable that lets someone set this to whatever they want seems like it would be a lot less confusing to people interested in using other arch settings.

**Comment by arrufat** [comment]
darknet has this small program, buildable with `nvcc`
``` c++
#include <cuda_runtime.h>
#include <cstdio>
int main()
{
  int count = 0;
  if (cudaSuccess != cudaGetDeviceCount(&count)) return -1;
  if (count == 0) return -1;
  for (int device = 0; device < count; ++device)
  {
    cudaDeviceProp prop;
    if (cudaSuccess == cudaGetDeviceProperties(&prop, device))
      std::printf("%d.%d ", prop.major, prop.minor);
  }
  return 0;
}
```
On my machine, in prints `6.1`, do you think we could use something similar to auto detect the cuda properties? Although I agree that doing `cmake -DDLIB_CUDA_CAPABILITIES=sm_50` might be better.

**Comment by davisking** [comment]
There really needs to be both.  If someone does -DDLIB_CUDA_CAPABILITIES=sm_50
it should use sm_50, but as a default running this kind of little program
and using its output is fine.  I'm suspicious this will mess people up.
E.g. they will build on a dev machine with a fancy GPU, a high arch setting
will get picked, and then the resulting binaries won't deploy to wherever
they were deploying them before.

That said, I'm willing to roll the dice on that if you want to put this
into a PR :)
