### ISSUE TITLE
Could you tell me how to detect objects in image which is not square using yolov3.dnn from dnn_yolo_train_ex.cpp, for example, whose ratio w:h = 5:1.Thanks!

### ISSUE THREAD

**Issue by newforrestgump001** [davisking/dlib#2440]
Could you tell me how to detect objects in image which is not square using yolov3.dnn from dnn_yolo_train_ex.cpp, for example, whose ratio w:h = 5:1.Thanks!

**Comment by arrufat** [comment]
The network doesn't actually enforce images to be square, you can forward them directly.
The main reason why it uses square images in the example, it's because we don't know the sizes and shapes of the images beforehand, so by using square sizes we can use batches of images.

It depends on what you want to do in the end. If you know all your images are going to have that aspect ratio, you should train a network using that size.
Otherwise, you can letterbox those images by padding the shortest side to make them square.
There's a function, [`letterbox_image`](https://github.com/davisking/dlib/blob/8a2c7442074339ac9ffceff6ef5a49e0114222b9/dlib/image_transforms/interpolation_abstract.h#L441-L472), that does just that, but [it was added](https://github.com/davisking/dlib/pull/2335) just after the latest release, so it doesn't appear in the documentation yet.

https://github.com/davisking/dlib/blob/8a2c7442074339ac9ffceff6ef5a49e0114222b9/dlib/image_transforms/interpolation_abstract.h#L441-L472

That's precisely what the example you mentioned is doing. Or maybe I misunderstood you.

**Comment by newforrestgump001** [comment]
Sincere thanks for your replay. My image size is 500 x 2560, I will have a try.

**Comment by newforrestgump001** [comment]
Thanks! I will try to modify to follow yolov3-tiny config or make the yolov3 network narrow.
