### ISSUE TITLE
Maybe it is necessary to reset the mini batch size in yolov3 train example.

### ISSUE THREAD

**Issue by newforrestgump001** [davisking/dlib#2441]
cout << "burn-in finished" << endl;
    trainer.get_net();
    trainer.set_mini_batch_size(batch_size); //it is new added and maybe also necessary.

**Comment by arrufat** [comment]
I am not setting the batch size in the lines you mention because it's already done in the `dnn_trainer` declaration:

https://github.com/davisking/dlib/blob/adca7472dfa2ed2df735dcc341fefb4cbe747f2d/examples/dnn_yolo_train_ex.cpp#L280-L284

So, it's not needed, as we are reusing the same trainer in the whole example.

**Comment by newforrestgump001** [comment]
Actually, during the second training, the batch size is set to 3, but the reason is unknown.
