### ISSUE TITLE
Considerations for run_multiple with HOG detectors

### ISSUE THREAD

**Issue by udupa-varun** [davisking/dlib#2467]
Not a bug report, just a few questions about how to use `run_multiple()` appropriately through the Python API. 
If this belongs elsewhere, please let me know.
My application is a multilabel, multiclass object detection problem.

I have multiple HOG detectors trained for a dataset using `train_simple_object_detector()`, mainly because I have multiple (but finite) aspect ratios to consider for object detection. I have variations in  `C` and `upsample_num_times` as well, (upsampled automatically by dlib because some of the object classes are tiny)

With that context, here are my questions:

1. I understand I should not be passing a list of these detectors to `simple_object_detector()` to run them together, because the window setup is different - and that I should be using `simple_object_detector.run_multiple()` instead to make it faster. Will doing this also respect the detectors' individual `upsample_num_times` parameter? Across the board I have 0, 1 and 2 upsamples for the saved detectors.
2. Is there a way to evaluate results from `run_multiple()` against a ground-truth `imglab` dataset? My understanding is that `test_simple_object_detector()` isn't meant for this case (because different window setup).
3. Is there a difference between `simple_object_detector.run_multiple()` and `fhog_object_detector.run_multiple()` that I should be aware of? Or does one internally call the other?
4. This last question is related more towards the scanning aspect, but is there a way to specify the sliding window stride, or the number of pyramid levels? What are the default values? I was unable to find it (in python at least). Is it restricted so people don't use unreasonable values?

Thank you btw, this is a great library! The simplicity is astounding.
I am interested in contributing to the library, but am not an adept programmer by any stretch of the imagination. 
I will however start taking bite-sized chunks and learn when I can from dlib.

That said, if I can contribute to your documentation in the meantime, please let me know.
(As I write this I shudder at the thought of documentation written by someone with virtually zero knowledge, but hopefully you get what I mean)

**Comment by davisking** [comment]
I honestly don't remember the details of how exactly this stuff works from python.  Dlib is really a C++ library, and the primary capability and documentation for this stuff is on the C++ API.  You should look at code in `dlib/tools/python/src` (that's where the python binding lives) to see what exactly it's doing and refer to the C++ docs for details.

There is always this complexity with python APIs since they have to kinda "do everything" inside the C++ code since pyhton is so slow.  E.g. you can't write a for loop in python that loops over any non-trivial number of things (e.g. pixels) since python is way too slow, or similarly use threads in any non-trivial way because of Python's GIL, or depend on any API that requires function inlining for efficiency, since that's a compile time optimization. The result of this is that python bindings tend to be saddled with a ton of optionality rather than being a small set of primitives that allow users to more simply build whatever they want.   Anyway, this is all to say yeah I know the python API is somewhat incomplete and some use cases are unclear from the python end :|  So I'm happy to accept PRs that make the python API nicer in some way.

**Comment by udupa-varun** [comment]
All right, I'll take a look at `dlib/tools/python/src` to see what's going on (and what my expectations should be from the python side)

This was helpful, thanks! The idea of "burdened functionality" on the python API definitely resonates. I understand the python GIL has been a long-standing annoyance (there has been a seemingly feasible proposal to remove the GIL, but that's a long term project).

I'll keep an eye out for stuff I can contribute in that direction then (nicer python API), based on what I can gather from the python binding. Low hanging fruit would probably be the "I wish the python documentation/examples had told me this" category, at least for functionality around the HOG+SVM object detector.

I'll close the issue now. Thanks again!
