### ISSUE TITLE
Why is dlib propagating compile options to targets linking to it?

### ISSUE THREAD

**Issue by oysteinmyrmo** [davisking/dlib#2504]
I have a target linking to `dlib` through Cmake on Windows. When setting up to compile with `clang-cl` and MSVC the following error occurs for my target:

```
(ClCompile target) ->
  clang-cl : error : unknown argument ignored in clang-cl: '-ftemplate-depth=500' [-Werror,-Wunknown-argument]
  clang-cl : error : unknown argument ignored in clang-cl: '-Xclang -fcxx-exceptions' [-Werror,-Wunknown-argument]
```
This happens because of the `PUBLIC` compile options at https://github.com/davisking/dlib/blob/master/dlib/CMakeLists.txt#L881, since these propagates to all targets linking to `dlib`. These options come from https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/set_compiler_specific_options.cmake#L136 and https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/set_compiler_specific_options.cmake#L153.

Is there a reason for doing this? I do not need these compile options on my targets. I would expect `dlib` (well, any library I link to) to set the compile options it needs for itself and not propagate any compile options onto my targets. If the comment at https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/set_compiler_specific_options.cmake#L135 is correct I expect the dnn example targets to set `template-depth` privately for themselves.

Notes:

- I include `dlib` simply by doing

```
add_subdirectory(submodules/dlib)
target_compile_options(dlib PRIVATE /W0)
```

- We use a slightly outdated version of `dlib`, but the behavior is verified to be the same for current master (`dlib/cmake_utils/set_compiler_specific_options.cmake` is identical on these parts).
- The version of `clang-cl` is the latest received from the Visual Studio Installer.
- Simply commenting out the compile options makes everything work fine on our end.
- (Side note: For some reason `dlib` compiles correctly with the same compile options and `clang-cl`, but does not recognize `template-depth` when compiling my target. The reason for this is unknown, but the question above still stands.)

**Comment by davisking** [comment]
These options are required to build for some versions of clang.  If the newer version of clang you are using on your platform doesn't support them anymore (which is a little bit surprising honestly, but maybe this is a special visual studio thing, rather than a clang thing) you are welcome to submit a PR that makes these options not set for your situation.

It is however not the case that libraries don't imply compile options for client code.  There are many others, not just these, that must be set in certain environments or with certain other configurations.   So not setting any "public" options is not a viable way to do this.

**Comment by oysteinmyrmo** [comment]
Closing this. I will create a pull request later with the changes that fixes these issues for us.
