### ISSUE TITLE
Visual studio 2022 installation 

### ISSUE THREAD

**Issue by NBarile** [davisking/dlib#2563]
Hi

Sorry for this issue, but i don't find anny instruction to install dlib in visual studio 2022.
Someone can help me ?

Thanks a lot !

**Comment by Sheldonfrith** [comment]
I'm also working on this, although your question isn't very specific. But here are some more specifics of what I'm dealing with...
- Developing c++ applications using Visual Studio 2022. 
- Debugging using the WSL (ubuntu) + Cmake that comes automatically with Visual Studio 2022

If I find a solution I'll post it here.

**Comment by Sheldonfrith** [comment]
Seems I've got it working, turned out to be quite simple, the problem was that I've only been working with c++ for about a week and so my knowledge of the fundamentals is still pretty weak. I spent a bit of time learning a bit more about CMake and was able to figure this out. 

Now, I am still having some issues in that ReSharper / Visual Studio intellisense does NOT WORK at all in any file using dlib, but the code compiles and runs fine, which is the most important thing obviously.

Here is how you do it with Visual Studio 2022 debugging on WSL with a CMake project...
1.  Download dlib on windows, not on your WSL install
2.  Copy the "dlib" folder (ie. "dlib-19.24/dlib") into your CMake project, put it into the same directory as your top level CMakeLists.txt file (unless you know what you're doing)
3.  Follow the instructions in this file for the next two steps (http://dlib.net/examples/CMakeLists.txt.html) ...
4.  add  the line `add_subdirectory(dlib dlib_build)` to your top level CMakeLists.txt file (I added this right below my `add_executable...` statement, although I'm not sure if that matters)
5. then if you already have a `target_link_libraries...` statement add `dlib::dlib`  into it, otherwise you need to add this line after the line from step 4 : `target_link_libraries(${PROJECT_NAME} dlib::dlib)`
6. then you are ready to go, use dlib in your project by `#include <dlib/graph.h` (as an example if you wanted functionality from the `graph` part of dlib)

**Comment by Sheldonfrith** [comment]
UPDATE: BETTER SOLUTION

So once again the extremely brief dlib install instructions (http://dlib.net/compile.html) turned out to be correct, with a little trial and error and more understanding....

To get dlib working better with Visual Studio (the solution I posted above lets you compile, but intellisense in Visual Studio gives a million errors for everything dlib related) you simply need to ...
- put the "dlib" folder within a container folder, not directly in your top level project directory
- change your top level CMakeLists.txt file like so:
     - remove the stuff you did if you followed my previous steps
     - add `"[name of folder wrapping dlib folder]/dlib/all/source.cpp"` in your list of files to compile (for example under `add_executable`
     - add `add_compile_definitions(DLIB_NO_GUI_SUPPORT=TRUE)` below that section (unless you install X11 stuff on your WSL, in which case you might be able to use the GUI features, I haven't tried it)
     - and then add this line below `target_include_directories(${PROJECT_NAME} PRIVATE [name of folder wrapping dlib folder])`

**Comment by NBarile** [comment]
Thanks you !!!

I'll try it later, for another project ;)

I don't close the issue, if you find another solution, please put it here :D

**Comment by Sheldonfrith** [comment]
My solution 100% worked for me, so I'm not going to be posting any other solution, probably can close the issue.
