### ISSUE TITLE
Please build the wheel files.

### ISSUE THREAD

**Issue by fotechv** [davisking/dlib#2895]
### Main idea

Hi there,
Could someone assist in building the dlib library into wheel files for easier installation and cross-platform compatibility? This would be extremely helpful for users who face challenges in compiling from source.
Thanks for your support!

**Comment by err-or** [comment]
You can checkout this [repo](https://github.com/z-mahmud22/Dlib_Windows_Python3.x) which provides the compiled wheels for Python 3.7-3.11 and Windows x64.

**Comment by davisking** [comment]
I would include such things but it is a never ending pain on my end.  In particular, different people have different hardware.  E.g. AVV or not, GPU or not, and especially GPU support requires somehow getting the appropriate nvidia libraries installed onto your system.  Which is a constantly changing thing based on what operating system and version of that operating system you happen to have.  So if you want to get a version of dlib that uses all the hardware acceleration your platform has to offer you should just build it yourself, which is typically not a big deal.  It just requires installing whatever the appropriate compiler is on your platform so that you can compile C++ code.  Then installing cuda and cudnn if you want to do anything with a GPU.
