### ISSUE TITLE
[Bug]: g++.exe: error: /bigobj: linker input file not found: No such file or directory

### ISSUE THREAD

**Issue by FlowLoveV** [davisking/dlib#2921]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.22

### Python version

3.11

### Compiler

MINGW 13.2.0

### Expected Behavior

I am using vcpkg to link dlib
```json
// vcpkg.json
// vcpkg version  2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
"dependencies": [
{
      "name": "dlib",
      "version>=": "19.22"
}
]
```
the CMakeLists.txt is as follows:
```cmake
find_package(dlib CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE dlib::dlib)
```
the build command is as follows:
```
"D:\clion\CLion 2023.3.4\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=D:\ProgramFiles\MinGW-64\mingw64\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:\ProgramFiles\MinGW-64\mingw64\bin\g++.exe  -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake 
"D:\clion\CLion 2023.3.4\bin\cmake\win\x64\bin\cmake.exe" --build D:\mashuo\project\nav\build --target NAV_TEST -- -j 30
```
it should be ok

### Current Behavior

build error message:
```
g++.exe: warning: /bigobj: linker input file unused because linking not done
g++.exe: error: /bigobj: linker input file not found: No such file or directory
```

### Steps to Reproduce

what should i do?

**Comment by davisking** [comment]
This seems like a problem with vcpkg, rather than dlib.  You should ask the people who maintain that.  I don't use it. it is for visual studio though.  So maybe vcpkg doesn't work with anything that isn't visual studio.

**Comment by davisking** [comment]
Or get dlib from the official dlib github.  That should work fine.

**Comment by jschueller** [comment]
you're probably trying to link msvc binaries with mingw, but they are incompatible

**Comment by nyoma-diamond** [comment]
Could we revive this issue? I'm running into it myself in a different and more repeatable context _without_ MinGW.
Specifically, when dlib is built using MSVC (`[clang-]cl.exe`), but then linked to using another (compatible) non-MSVC compiler (i.e., `clang[++]`), the `/bigobj` setting persists outside of the relevant context, causing an error.

In my case, I'm building dlib using MSVC (`cl.exe` to be specific) for development on my system / within my development environment. However, when compiling my project I intend to use `clang[++]`. Other libraries handle this just fine, but in dlib the `/bigobj` option persists when attempting to run `clang[++]` on my project, causing the following error:

```
Cannot get compiler information:
	Compiler exited with error code 1: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin\clang++.exe -xc++ -isystemC:/Users/Nyoma/Documents/MyProject/build/debug/vcpkg_installed/x64-windows/include -O0 -std=gnu++20 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview /bigobj -fpch-preprocess -v -dD -E
	clang version 19.1.5
	Target: x86_64-pc-windows-msvc
	Thread model: posix
	InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin
	clang++: error: no such file or directory: '/bigobj'
```

The problem appears to come from the contents `active_compile_opts` being injected into the generated `dlib.cmake` at compile time for dlib, rather than at build time for the consumer, causing `/bigopt` to be used even when the context has switched to no longer use MSVC.

In the generated `dlib.cmake` file:
```CMake
set_target_properties(dlib::dlib PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:/bigobj>"  # <-- Here
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "LAPACK::LAPACK;BLAS::BLAS;\$<LINK_ONLY:ws2_32>;\$<LINK_ONLY:winmm>;\$<\$<NOT:\$<CONFIG:DEBUG>>:${VCPKG_IMPORT_PREFIX}/lib/libpng16.lib>;\$<\$<CONFIG:DEBUG>:${VCPKG_IMPORT_PREFIX}/debug/lib/libpng16d.lib>;\$<\$<NOT:\$<CONFIG:DEBUG>>:${VCPKG_IMPORT_PREFIX}/lib/zlib.lib>;\$<\$<CONFIG:DEBUG>:${VCPKG_IMPORT_PREFIX}/debug/lib/zlibd.lib>;\$<\$<NOT:\$<CONFIG:DEBUG>>:${VCPKG_IMPORT_PREFIX}/lib/jpeg.lib>;\$<\$<CONFIG:DEBUG>:${VCPKG_IMPORT_PREFIX}/debug/lib/jpeg.lib>"
)
```

This is caused by `/bigobj` being appended to the `active_compile_opts` variable in `dlib/cmake_utils/set_compiler_specific_options.cmake`:
```CMake
if(MSVC)
   #...
   list(APPEND active_compile_opts "/bigobj")
   #...
endif()
```
and then added to the target compile properties via the following in `dlib/CMakeLists.txt`:
```CMake
if((MSVC AND CMAKE_VERSION VERSION_LESS 3.11))
   target_compile_options(dlib PUBLIC ${active_compile_opts})
   target_compile_options(dlib PRIVATE ${active_compile_opts_private})
else()
   target_compile_options(dlib PUBLIC $<$<COMPILE_LANGUAGE:CXX>:${active_compile_opts}>)
   target_compile_options(dlib PRIVATE $<$<COMPILE_LANGUAGE:CXX>:${active_compile_opts_private}>)
endif()
```

((Side note 1: `set_compiler_specific_options.cmake` also appends `/MP` into `active_compile_opts` right after `/bigobj`, but it doesn't seem to appear in `dlib.cmake` or the `clang++` call for which the error occurs. Not really sure why))

This appears to effectively apply the assumption that if MSVC was used to compile dlib initially, then any consumer must also be using MSVC, which is not necessarily true. This also introduces the problem of being unable to distribute pre-compiled dlib binaries with their generated config/target files for Windows unless we mandate that the consumer is using MSVC. If this behavior is expected for some reason, it should really be documented, but in practice it would be much better to just remove this restriction altogether.  ((Side note 2: shouldn't `$<$<COMPILE_LANGUAGE:CXX>:` be applied to each element of `active_compile_opts[_private]`? The current approach only applies it to the first option if multiple are present)). 

In practice, I believe this would be solved by restructuring the relevant checks so that the necessary `target_compile_options` calls are performed by `dlib/cmake_utils/dlibConfig.cmake.in` / `dlibConfig.cmake` when dlib is linked/consumed rather than initially compiled, and/or via via `CMAKE_C[XX]_FLAGS`, as these are the approaches I see from other libraries (namely CGAL). ((Side note 3: Despite having functionality for it, other dependencies that I'm using don't seem to add `/bigobj` to `INTERFACE_COMPILE_OPTIONS` even when using MSVC exclusively. I'm not super well-versed in this side of CMake/compiler interaction so I'm not 100% clear what's necessary or not here, but I thought I'd mention it)).

Admittedly, I am running into this error via vcpkg, which @davisking has already said the port for which is not developed by the maintainers of this library directly; _however_ in practice I expect this issue would persist even outside of the vcpkg context due to the `/bigobj` being directly applied to the `dlib.cmake` target at compile time (I just don't currently have a workflow set up to test this outside of vcpkg).

### Version details:

 - dlib: 20.0.0
 - python: 3.12.7
 - `cl.exe`: 19.44.35217
 - clang: 19.1.5

**Comment by nyoma-diamond** [comment]
On second thought, I'll reopen this as a new issue: #3125
