### ISSUE TITLE
[Bug]: DLib build error

### ISSUE THREAD

**Issue by Zagreus9723** [davisking/dlib#2954]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24.4

### Python version

3.11.5

### Compiler

CMake

### Expected Behavior

The expected behavior was for the DLib pip package to install and compile.

### Current Behavior

The installation and build fails with the error
`ValueError: path 'dlib/CMakeLists.txt/' cannot end with '/'`

### Steps to Reproduce

Run pip install dlib

**Comment by Zagreus9723** [comment]
@davisking Any updates?

**Comment by davisking** [comment]
I can't say from just what you posted.   I would expect there to be more.  Try using `pip` with `--verbose`.  There should be more to the error message than that.   I will note that lots of people use dlib on windows and when errors are reported in building it's always just that visual studio or cmake is installed wrong or missing.  So that's probably the issue here too.
