### ISSUE TITLE
Unexpected behaviour of INSTALL target under Windows

### ISSUE THREAD

**Issue by bonext** [davisking/dlib#306]
Both release and debug builds of the library have the same name, so on windows `INSTALL` target overwrites the built libraries. 
This means a developer needs to generate separate projects for release and debug when using CMake's `find_package`

**Comment by davisking** [comment]
If there is some reasonable way to make it behave better then I'll accept a pull request for it.  But more generally, you should really statically compile dlib into your application on windows since the way visual studio (assuming you are talking about visual studio) does shared libraries is a total mess.  See this page for a great discussion of visual studio's problems http://siomsystems.com/mixing-visual-studio-versions/.

**Comment by e-fominov** [comment]
When building dlib, you can pass "CMAKE_INSTALL_PREFIX" argument to cmake:
```
cmake .. -DCMAKE_INSTALL_PREFIX=c:\dlib_release
cmake --build . --target install
```
And you can change folder to have debug build in some other directory

When you will need to use dlib in your project - pass "CMAKE_PREFIX_PATH" argument when building your project:
```
cmake .. -DCMAKE_PREFIX_PATH=c:\dlib_release
```

Same situation if you have different versions of Visual Studio
But If you use MinGW - you can install release dlib and use it with both debug and release configurations of your project (it should be built with MinGW too)

Most functions of Dlib are header-based. So if you want to use some heavy functions like face detection or DNN in Debug Visual Studio project you will get very low performance.
The best way is to build some Dll in Release mode (or even better=works faster with MinGW) with functions from headers and use this Dll in your Visual Studio project

**Comment by davisking** [comment]
You can't really build in release mode in visual studio and then use that release mode dll in a debug mode visual studio program.  I mean you can try, but it might crash since you will be mixing two different visual studio runtimes.  I should also emphasize that there are at least 8 different visual studio runtimes, and you can't mix them with each other.  If you want to create separately compiled libraries with visual studio then you have to contend with this multiple runtime problem visual studio has.   But like I was saying, you are must better just avoiding this by compiling everything together in one application rather than trying to make separately compiled libraries.
