### ISSUE TITLE
cmake install vs2015 debug/release

### ISSUE THREAD

**Issue by nuke160** [davisking/dlib#312]
I build dlib with cmake and vs2015 (DLIB_USE_CUDA ON).
When I install the release version it overwrites the debug dlib.lib file in the install/lib folder.
I think this is intended but it produces errors when using visual studio 2015 and the new dnn feature.
Here is a short demo.

CMakeLists.txt: 
```
cmake_minimum_required(VERSION 2.8)
project (install_bug_demo)
FIND_PACKAGE(dlib REQUIRED)
add_executable (demo main.cpp)
INCLUDE_DIRECTORIES(${dlib_INCLUDE_DIRS})
TARGET_LINK_LIBRARIES(demo ${dlib_LIBRARIES})
```
main.cpp:
```
#include <dlib/dnn.h>
int main() {}
```

When I install the **debug** version of dlib compiling the debug version of this demo is fine but I get the following error compiling the **release** version of this demo:
`dlib.lib(threads_kernel_shared.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in main.obj`

When I install the **release** version of dlib I then get the following error while compiling the **debug** version of this demo: 
`error LNK2001: unresolved external symbol USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives`

**Comment by davisking** [comment]
This is not a dlib bug.  It's just how visual studio works.  You aren't allowed to mix debug and release code together in a project.  So this has nothing to do with visual studio.

**Comment by nuke160** [comment]
Maybe I was not clear. I know that I'm not allowed to mix debug and release code.
In previous versions of dlib (e.g. 18.17 the install project produced 4 dlib.lib files in 4 different folders (lib/Debug, lib/MinSizeRel, lib/Release, and lib/RelWithDebInfo). That was fine and I could link each lib file to my project.
The dlib version 19.2 however produces only one dlib.lib file (in folder lib).
Is this intended? Do you want me to build two different install folders for debug and release.
This wouldn't be hard to do but cmake will not find the debug and the release version with the same library name in two seperate installations.

**Comment by davisking** [comment]
dlib 18.17 didn't have any install target in it's cmake file so I don't see
how you could have done that.  What did you type to do this with 18.17?

I would setup your cmake project like the examples show, where you
statically build dlib along with the rest of your project rather than
separately compiling it.  This avoids all the problems visual studio has
with separately compiled libraries.  I should also point out that there are
many ways to accidentally create lib files in visual studio that silently
link and seem to work only to produce programs that crash once a week and
are very hard to debug.  This is also a great article about some of this
http://siomsystems.com/mixing-visual-studio-versions/.

**Comment by nuke160** [comment]
You're right. dlib 18.17 doesn't have any install target. However, when I set CMAKE_INSTALL_PREFIX it will copy the 4 dlib.lib files into that folder. I then wrote a finddlib.cmake file to link them to my project.

Thanks for the hint. I managed to include dlib into my project. If building dlib along with my project is your favored solution, why do you provide the install target in dlib 19.2? Or is it just not compliant with vc14?

**Comment by davisking** [comment]
Someone contributed the install target.  I resisted it for years because I
know most users don't understand the issues surrounding C++ ABI
portability, dynamic linking, the C++ one definition rule, and so forth.
That leads to confusing compiler/linker/runtime errors which then get
emailed to me, even though they have nothing to do with dlib.  However, on
unix platforms the install target is a sensible thing to have since unix
has a sensible way of dealing with shared libraries.  It's still a complex
issue, but isn't full of remotely as many hidden bombs as visual studio's
DLL mechanism.

My general advice is still to build everything together since the dlib
built time is not significant and doing so avoids any possibility of mixing
incompatibly compiled object files. This issue of mixing files compiled in
different and incompatible ways is far and away the number one complaint
people have about building C++ projects.  But if you compile everything at
once it's a non-issue since you have consistent compiler settings across
the entire build.  That kind of build system is very easy to get right,
even for novice users.  However, builds consisting of multiple
independently compiled object files/static/shared libraries require
somewhat deep C++ expertise and understanding of your compiler to get
right.  The advantage is *sometimes* faster compiles. However, there are a
lot of ways to speed up a build that are much easier to get right.
