### ISSUE TITLE
AttributeError: 'module' object has no attribute 'image_window'

### ISSUE THREAD

**Issue by great-thoughts** [davisking/dlib#37]
Hi, 
I tried to run face_detector in python_examples, but I get the following error:
```
Traceback (most recent call last):
  File "face_detector.py", line 44, in <module>
    win = dlib.image_window()
AttributeError: 'module' object has no attribute 'image_window'
```
I tried deleting the build folder and running again ./compile_dlib_python_module.bat but I still get the same error message. 
Any help would be appreciated.

**Comment by davisking** [comment]
You must have compiled dlib without the X11 GUI option.  When you compile it it should print a message saying that it's not going to have GUI support and it tells you what to do to.  But if you do nothing then you get a copy of dlib without any kind of GUI features which is what you have.

**Comment by great-thoughts** [comment]
Thank you. Installing Quartz solved the problem.

**Comment by adimittal** [comment]
*****************************************************************************
 *** DLIB GUI SUPPORT DISABLED BECAUSE X11 DEVELOPMENT LIBRARIES NOT FOUND ***
 *** Make sure XQuartz is installed if you want GUI support.               ***
 *** You can download XQuartz from: http://xquartz.macosforge.org/landing/ ***
 *****************************************************************************

**Comment by davisking** [comment]
Yep, that's the message the build scripts print. Somehow lots of people see that message and still don't understand what to do to enable GUI support. :(

**Comment by adimittal** [comment]
1. They might not realize they need GUI support
2. The message is near the top of the long output, move it to the bottom if you don't want fewer people to ignore it :)
