### ISSUE TITLE
drectangle with the size < 1

### ISSUE THREAD

**Issue by e-fominov** [davisking/dlib#463]
I was trying to use drectangle with some normalized coordinate system, where x/y are in range 0..1. This allows me to make processing independent from image resolution, because modern CCTV cameras have multiple output video streams of different resolution

Current drectangle contract says that its size can't be less than 1:
```C++
 drectangle centered_drect (
        const vector<double,2>& p,
        double width,
        double height
    );
    /*!
        ensures
            - returns a rectangle R such that:
                - center(R) == p
                - if (width < 1 || height < 1)
                    - R.width() == 0 
                    - R.height() == 0 
                    - R.is_empty() == true
                - else
                    - R.width() == width
                    - R.height() == height 
    !*/
```

Is there any way to change this? It would be nice to have rectangle primitive without such strong restriction and inventing the wheel with some new rectangle class does not look interesting

The main problem I see are right() and bottom() values. Now they are pointing to a positions *inside* rectangle. OpenCV's implementation makes simple : right = left + width, while dlib's: right = left + width - 1

I can imagine some other situations where this can be usefull:
1. DNN can produce drectangles (YOLO, SSD for example are working this way)
2. some affine-transform of drectangle

**Comment by davisking** [comment]
Yeah, the drectangle is weird in that way.  But it's because the rectangle, that has integer coordinates, works this way.  And this makes them behave in the same way.  For example, a rectangle(1,1,1,1) is the rectangle that contains exactly the pixel point(1,1).  If it were defined the opencv way the integer rectangle object would have an odd API.  Since the dlib::rectangle has been around forever we can't change this even if we wanted to anyway.  

The first version of the drectangle I made behaved as you suggest, which is how you would expect something with continuous coordinates to work.  But then when it's converted to or from dlib::rectangle objects it gets all weird and wrong, giving bad and surprising behavior in a number of cases.  So I changed it to work the way it does now to make dlib::rectangle and dlib::drectangle compatible.

Although, the general use case for dlib::rectangle and dlib::drectangle is to represent boxes in images, where the coordinates are always integer valued and never in the range 0..1.   For that it's convenient.  But yeah, as a general rectangle the drectangle is weird.

**Comment by e-fominov** [comment]
Looks like the only solution is to have a new class copied from drectangle with minor changes.
Do you think it will be useful in dlib now?

**Comment by davisking** [comment]
Maybe.  It might just be more confusing if you add another.  You would have to remove any conversions between a new class and rectangle and drectangle.  I can see that being a source of confusion.  There are also probably some of the utility functions for drectangle that don't make any sense for a general rectangle.  

Anyway, I'm not sure.  If you want to propose something I'll take a look :).

**Comment by e-fominov** [comment]
What if we will change drectangle's interface this way?

```C++
        template<bool inside=true>
        double right()  const { return inside ? r : r + 1;}
```

This will make it's default implementation work the same way as original and leave it 100% compatible with rectangle, but will also allow having size < 1

**Comment by davisking** [comment]
How does someone use that though?  They call all the regular utility
functions and get the old behavior.  width() still uses the old behavior,
etc.

**Comment by e-fominov** [comment]
i am thinking, if we can change drectangle's internals to make it work with size < 1 and keep it 100% compatible with rectangle.

drectangle can be constructed from dlib::centered_drect 
```C++
drectangle r = centered_drect(dpoint(1,1), 0.5, 0.5);
```
this will not produce any error messages and will make l=1.25, r=0.75, t=1.25, b=0.75, is_empty = true, width()=0, height()=0

now `width = r - l + 1`. what if we will change drectangle's behaviour to have `width = r - l`, and `right()=r-1`; ?
this way we will  keep it compatible with rectangle and all other functions
yes, this way we should also change some other interface functions (is_empty, width, height, right, left ...), but their result will be identical to current implementation except the situation when size < 1

**Comment by davisking** [comment]
That seems even more weird than the current behavior though.  Say you make a drectangle by giving it two points.  Then you go ask it what the right boundary is and it subtracts 1 from the right boundary value you supplied in the constructor.  That's way worse :/

**Comment by davisking** [comment]
I mean, fundamentally, right now a drectangle is just a set of 4 numbers.  It doesn't modify them or do anything funny to them.  It's just that the width() and height() member functions have this odd behavior because of compatibility requirements with the discrete coordinate system used by rectangle.

**Comment by davisking** [comment]
But you can still put whatever values you want in the drectangle.

**Comment by e-fominov** [comment]
Thank you for the explanation. Looks like there is no simple and compatible way to modify the drectangle for this goal

**Comment by davisking** [comment]
No problem.  I already when through all this trying to make the drectangle like you would expect but it just makes all these compatibility problems with the rectangle :(

You would be better of using an entirely different object to do this kind of stuff.
