### ISSUE TITLE
DLib Community Channels

### ISSUE THREAD

**Issue by RoyiAvital** [davisking/dlib#504]
Hi,

@davisking , I recently found DLib and wanted to say it is great, really.

I think Dlib deserves better community facilities than SourceForge communities.
I'd like to suggest:

1. DLib Gitter Channel.
2. DLib Forum based on [Discourse](https://www.discourse.org/) (With Math Equation support using [MathJaX](https://www.mathjax.org/) with the [MathJaX Plug In](https://meta.discourse.org/t/mathjax-plugin-supports-math-notation-using-latex/12826)).

These solutions will enable better knowledge flow between DLib's users.

Thank You.

**Comment by davisking** [comment]
Thanks, but I'm not going to spend my time on a gitter channel.  I'm way too busy for that.  And discourse is apparently something that costs money.  So not doing that either.  

There are already lots of forums on the internet for people to talk about software and machine learning.  Why do you think we need another?

**Comment by RoyiAvital** [comment]
Hi,

I don't think you must be in the Gitter channel.
Just once you open it it will be official one for Dlib.
The people who should be there are Dlib users.

I was under the impression Discourse is free (Or at least can installed and used free).

The idea was to replace Sourceforge ancient forums and to give Dlib's users better place to share information about the usage of Dlib.

I, for one, would love to have such channels.

Thank You.

**Comment by davisking** [comment]
Well, I'm not going to idle in a chat room, so since I'm not going to use it I'm not going to set it up.

Also, there are two kinds of questions.  Bug reports or issues specifically related to some problem in dlib (i.e. things you can post to github) and things that are not (e.g. general programming or machine learning questions).  The first category is nicely served by github issues.  People with the other kind of question, "how do I program a computer?" or "can someone teach me machine learning?" would be much better served by using some other resource than a dlib chatroom.  For example, by reading a good textbook, taking a machine learning or programming class, or even asking on stack overflow.

**Comment by RoyiAvital** [comment]
@davisking ,
I see your point and appreciate you take time to explaining it.

I still thinks there is a room for Forum for Dlib users (There is actually, on SourceForge, yet the platform isn't welcoming).  
I understand you have bad experience with many people trying to get support form you.

But my intention was different.
A community which each helps others.

For instance, how about questions about your method for objects detection learning?
About the exact procedure of Dlib reagrding some functions?

I feel I'd be happy to have such place.

Thank You.
