### ISSUE TITLE
Dlib GPU support for Python

### ISSUE THREAD

**Issue by sskgit** [davisking/dlib#522]
I am working on Face Recognition github repo. There is a reference for compiling dlib for GPUs. 
https://github.com/ageitgey/face_recognition.

For Python would like to know what is the best way to compile dlib with GPU support.

**Comment by davisking** [comment]
When you compile it will print messages saying what it's doing.  It will say something like "Using CUDA" or that it's not using CUDA because you are missing cuDNN or the CUDA dev kit.  

So, by default, it will use the GPU unless you don't have the CUDA tooling installed.  If that's the case it will print out messages that clearly indicate that's happening and tell you what to do fix it.

**Comment by sskgit** [comment]
Thanks @davisking

**Comment by kimgenegaby** [comment]
After stated "Using Cuda" and compiled successfully, when executing "import dlib", the error message stated,"ImportError: DLL load failed." This version is 19.9 latest version.

**Comment by rw86347** [comment]
Wow, I am in the exact same boat.  What was your final outcome?  How did you finally resolve the issue?
