### ISSUE TITLE
test_object_detection_function slow

### ISSUE THREAD

**Issue by amincheloh** [davisking/dlib#544]
Hi,
Thanks for good library. I have been using the dlib library for a few week particularly the object detection.  fhog_object_detection_ex example the training time is very fast I am very impressed. however, testing time is slow. After looking in dlib source I think because of test_object_detection_function  use only single core CPU.
Do you have any suggestion to improve testing speed?

**Comment by e-fominov** [comment]
First of all, have you read this? http://dlib.net/faq.html#Whyisdlibslow

Anyways, test_object_detection_function takes a lot of time because it makes a lot of computations with running detector over all images in test dataset and its performance is limited by trained detector. The larger detector you will train, the larger is dataset- the more time it will take
I recommend you to measure the performace of detector separate from test_object_detection_function - this will make you understand the situation

The overall FHOG detector performance depends on
1. image resolution
2. pyramid size
3. detection window size
4. detector filters count

And yes, it is not multi-threaded, but you can run detector yourself from multiple threads by creating several instances of detector - one per thread. Calling same detector from different threads is not safe

**Comment by amincheloh** [comment]
Yes, I read the FAQ, and just move the other higher perf PC.
