### ISSUE TITLE
Inconsistency reading BMP file

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#552]
I set up a test that shows a problem I encountered in dlib while reading a bmp image.
I tested with OpenCV to be sure the problem wasn't specific to the image I was using.
I also provide the image used for this test
https://mega.nz/#!fZRzSD6I!pU8S34XKersImgaLsuNh8EiCPh9G12d7K56MKjrUaXk
(for some reason, GitHub does not allow me to upload a zip file...)

- `img_1.bmp`: the tested image
- `dimg.png`: the output image using Dlib
- `cimg.png`: the output image using OpenCV

The code:
```cpp
#include <dlib/image_io.h>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace dlib;

int main(int argc, char** argv) {
    cv::Mat cimg;
    cimg = cv::imread(argv[1], cv::IMREAD_COLOR);
    cv::imwrite("cimg.png", cimg);

    dlib::matrix<rgb_pixel> dimg;
    dlib::load_image(dimg, argv[1]);
    save_png(dimg, "dimg.png");
    return 0;
}
```

Am I reading the bmp image correctly?
Thanks in advance.

**Comment by davisking** [comment]
Yeah, you are doing it right.   BMP is a crazy format, so I'm not surprised there are bmp files that don't load right.  If you look at the code you will see that there are a huge number of possible code paths that are all pretty much unrelated because BMP is more like 20 different formats all jammed together in Microsoft's history.

**Comment by arrufat** [comment]
Thanks for the quick response, I'll just use OpenCV to load these files as a workaround.
