### ISSUE TITLE
Project idea: Provide support for OpenCL 1.2 devices

### ISSUE THREAD

**Issue by viper7882** [davisking/dlib#652]
Hi @davisking ,

Hugh Perkins has created [Coriander](https://github.com/hughperkins/coriander-dnn) that could run NVIDIA® CUDA™ code on OpenCL 1.2 devices. You might want to take a look if that suits your need to connect your Deep Learning software to OpenCL 1.2 devices. Kindly attribute his name and his contribution in case if you plan to use his work.

**Comment by davisking** [comment]
Unless it converts all the rest of the NVIDIA software stack like cuDNN and cuBLAS, it's not going to work.  But if it does then someone should submit a PR with it ;)

**Comment by hughperkins** [comment]
> Unless it converts all the rest of the NVIDIA software stack like cuDNN and cuBLAS

It does ;-) . https://github.com/hughperkins/coriander

**Comment by hughperkins** [comment]
well:
- A partial implementation of NVIDIA® CUDA™ cuDNN API for OpenCL 1.2 is at https://github.com/hughperkins/coriander-dnn
- A partial implementation of NVIDIA® CUDA™ cuBLAS API for OpenCL1.2 is at https://github.com/hughperkins/coriander
- A compiler and runtime to run NVIDIA® CUDA™ code on OpenCL™ 1.2 devices is also at https://github.com/hughperkins/coriander

**Comment by davisking** [comment]
I'll believe it when someone submits a PR that works ;)

**Comment by awiebe** [comment]
@davisking
Would it be acceptable to **partially patch it for OpenCL** support of just the bits I'm using?

I assume that dlib abstracts away the vector math from the actual desired computation, so it can easily switch between CUDA and non-CUDA support, it would probably be easiest to patch it there.

I'm using the face feature predictor and computing a face descriptor with the face recognizer in the python wrapper.  I'm a few layers of abstraction away from the underlying problem here, but supposing I was willing to partially implement OpenCL support **where in the guts of dlib should I look?**

**Comment by davisking** [comment]
You could certainly do that.  Yes, there is an interface layer, but you are
still talking about writing a lot of OpenCL.  Like you need to write
efficient convolution operations and all that stuff. Look at the dnn
layers.  Their interface is fully documented and they are the things that
need to be implemented for every underlying hardware platform.

**Comment by hughperkins** [comment]
If you're going to do that, the easiest way to do convolution is to use GEMM
- you can use eg CLBlast to get a GEMM implementation, https://github.com/CNugteren/CLBlast (there's also clBLAS, from AMD, but personally I find Cedric Nugteren's implementation cleaner, and much easier to build too)
- you'll need to do the im2col thing, as described approximately at https://petewarden.com/2015/04/20/why-gemm-is-at-the-heart-of-deep-learning/

You can see an implementation of these things in practice at https://github.com/hughperkins/coriander-dnn/blob/master/src/cocl_dnn_gemm.cpp#L158-L268 (and backprop etc are in the same file). There is a test script to run this at https://github.com/hughperkins/coriander-dnn/blob/master/test/gtest/test_dnn_conv.cpp . It's a bit mangled, since it publishes a cuDNN interface, but you can probably see from the tests how it works. Ish...

**Comment by davisking** [comment]
I am skeptical that im2col and GEMM can give reasonable conv performance.
I know people do this, but it implies a lot of expensive copying and data
shuffling in addition to the actual conv computation.

**Comment by davisking** [comment]
4x slower is a lot.  But yes, in a pinch im2col and GEMM is better than
nothing.

**Comment by rajhlinux** [comment]
This is great, this means I can put my AMD GPU into good work while offloading the CPU thanks to OpenCL...
