### ISSUE TITLE
Multi-class loss_mmod

### ISSUE THREAD

**Issue by reunanen** [davisking/dlib#659]
@davisking, thanks again for this awesome library.

You write [here](https://github.com/davisking/dlib/issues/252#issuecomment-249832149):

> I haven't made the loss_mmod multi-class yet.  It's a minor change though
> and will be in dlib in the near future though :)

I guess this does not exist yet? At least couldn't find anything.

I'd be happy to try to contribute, however it seems you already have a clear idea how it should be done, so I guess I'd be better off waiting for your implementation?

**Comment by davisking** [comment]
I haven't done it yet.  I'm working on the multi-aspect ratio update at the moment.  Which is itself not that complicated.  I'm fairly confident the code is right, but I haven't pushed it to github yet since I'm not done testing it.  And testing DNN tooling takes forever because training is so slow.  

Anyway, I'll push the multi-aspect ratio mmod in a week or two at the most unless I find something wrong with it, which seems unlikely at this point.  Then I'll update it for multi-label support after that, which is a lot simpler and shouldn't require as much tedious testing.

**Comment by reunanen** [comment]
The multi-label support is now in `master`, and seems to work great. Thanks a lot, Davis!
