### ISSUE TITLE
auto_ptr is deprecated in >= C++11

### ISSUE THREAD

**Issue by severin-lemaignan** [davisking/dlib#67]
`auto_ptr` are deprecated in recent versions of C++ (c++11 and above).

`dlib` uses them in four files:
```
dlib/smart_pointers/shared_ptr_thread_safe.h
dlib/smart_pointers/shared_ptr_thread_safe_abstract.h
dlib/smart_pointers/shared_ptr_abstract.h
dlib/smart_pointers/shared_ptr.h
```

While not critical, it causes recent compilers to emit deprecation warnings every time one includes dlib in a project, which is annoying.

This is a more serious issue for users who want to compile their code with `-Werror`.

Remediation options include:
- putting the offending code behind a guard (`#if __cplusplus <= 199711L`)
- removing the offending code
- removing completely dlib's custom smart pointers to use standard ones (`std::shared_ptr` and `std::unique_ptr`) -- this would raise the minimum compiler requirements to C++11.
- selectively ignore these warnings by surrounding offending code with:
```cpp
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
//...
#pragma GCC diagnostic pop
```
(note that this is more like a workaround, and besides, a GCC-only one)

**Comment by davisking** [comment]
Yeah, that is annoying.   I want to eventually deprecate and hide these dlib smart pointers once C++11 becomes mandatory for dlib as a whole.  But compiler support is not widely spread enough for that yet.  So right now I would favor the pragma approach since that seems least likely to disrupt existing users.  Can you test that out and submit a pull request for it? :)
