### ISSUE TITLE
build error : duplicate symbol for architecture x86_64

### ISSUE THREAD

**Issue by sharma14skss** [davisking/dlib#676]
having build error on os x el capitan ,opencv-2.4.11 installed already

```
[ 34%] Built target dlib
[ 35%] Linking CXX executable webcam_face_pose_ex
duplicate symbol _jpeg_natural_order in:
    dlib_build/libdlib.a(jutils.cpp.o)
    /usr/local/share/OpenCV/3rdparty/lib/liblibjpeg.a(jutils.c.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/webcam_face_pose_ex.dir/build.make:143: webcam_face_pose_ex] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/webcam_face_pose_ex.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
```

**Comment by xsacha** [comment]
Can you build either dlib or opencv without jpeg support? BUILD_JPEG=OFF
Or use shared library for either jpeg, dlib or opencv?

The problem is that both libraries are including jpeg statically.

**Comment by davisking** [comment]
There are cmake options that let you toggle JPEG on and off.  Just set the options however you want before you build.  cmake has a nice GUIs that lets you toggle them called ccmake and cmake-gui.

Also, this wouldn't happen if you had libjpeg installed on your system ahead of time since that would allow both dlib and opencv to link to that one copy of libjpeg.
