### ISSUE TITLE
libpng support for macOS Sierra (10.12.5)

### ISSUE THREAD

**Issue by andrew-k-21-12** [davisking/dlib#721]
I use the latest repo version of the dlib and stated in the title OS. It can be spotted that some users have encountered this issue too (using some small internet search), for example: https://github.com/davisking/dlib/issues/106.

On some systems when we try to load PNG images using a `load_image` function, an exception with a comment 

> png_loader: parse error in file some_file.png

 is thrown. If we debug this function, we'll be able to see that an error occurs (created `png_structp` structure is `NULL`) on the line:

`ld_->png_ptr_ = png_create_read_struct( PNG_LIBPNG_VER_STRING, NULL, &png_loader_user_error_fn_silent, &png_loader_user_warning_fn_silent );`

of "dlib/dlib/image_loader/png_loader.cpp" file. 

I could fix this by manually replacing `PNG_LIBPNG_VER_STRING` with a version string of the latest libpng installed in my system via Homebrew:

`ld_->png_ptr_ = png_create_read_struct( "1.6.30", NULL, &png_loader_user_error_fn_silent, &png_loader_user_warning_fn_silent );`

Now PNG images' loading is correct, but I'm afraid that this solution is not quite clear. I'll try to make a better solution, please let me know, if a better way of such solution is already available.

**Comment by davisking** [comment]
This is almost certainly happening because you have multiple versions of libpng installed on your machine.  The code is compiled against one version of libpng, then run with another which then gives you an error because the versions don't match.  The right solution is definitely not to hack the version string to match.  The whole point of that version number is to cause an error in this specific case.  If you just hack it in it's very likely something bad will happen, like random program crashes.  

I just updated the dlib error message to be more informative when this happens.  It will now print the two versions of libpng in play here and tell you this is happening.

The right think to do is to make sure you only link to one version of libpng and that it's the version you are compiling with your code.

**Comment by andrew-k-21-12** [comment]
Thank you, @davisking , I'll try an updated version and answer here if some new information will be available for this issue.
