### ISSUE TITLE
Is this the correct approach to solving a face recognition problem?

### ISSUE THREAD

**Issue by abhisheksoni27** [davisking/dlib#741]
**What's the problem?** : I want to build a system which takes in an image and compares it to ten others and figures out who it is.

I read this blog-post: http://blog.dlib.net/2017/02/high-quality-face-recognition-with-deep.html
And I am using the python file mentioned in it. 

The example code only deals with getting a face-descriptor(which is awesome)

To extend the sample to my use case, I figured all I have to do is run the example for the images in my dataset, and then save the face-descriptor (How?!).

The next time, in the actual run of the application, it will open all descriptors, compare the Euclidean Distance and classify.

Is this the right approach?

Or do I have to train a model myself, just like the provided resnet.dat file was generated?

**Comment by davisking** [comment]
Yes, that's what you do.  You don't train a new DNN, you can use the provided model.  Although, it's common and useful to us a linear SVM to decide if a new face matches a previous one rather than Euclidean distance.  However, sometimes Euclidean distance is the right thing to do.  It really depends on your application.

**Comment by abhisheksoni27** [comment]
Thank you, Sir. I'd look into linear SVM's performance compared to Euclidean distance. Thanks for the suggestion.

**Comment by abhisheksoni27** [comment]
Also, if it is not much trouble, How do I save the generated face descriptor?
