### ISSUE TITLE
Support for AMD GPUs

### ISSUE THREAD

**Issue by azmathmoosa** [davisking/dlib#743]
Thanks for the great work!  This is more of a feature request, but is it possible to port dlib to use AMD gpus using their HIP tool here.
https://github.com/ROCm-Developer-Tools/HIP

According to this [article](http://gpuopen.com/ported-caffe-hip-heres-happened/), porting Caffe from CUDA to HIP was done 99% automatically by the tool.  The rest 1% was only 200 lines of code pertaining to cuDNN.  AMD's alternative is MIOpen and they have published this [guide](https://github.com/dagamayank/ROCm.github.io/blob/master/doc/miopen_porting_guide.pdf) showing the equivalent API calls.

Would it be worth it or is it too much work?

Once again, thanks a lot for the great library.

**Comment by davisking** [comment]
There is a lot of stuff in cuDNN, more than 200 lines.  So you have to port that part too.  If someone wants to do this that would be great, but I'm not interested in running on AMD GPUs.

**Comment by OranjeeGeneral** [comment]
Good to see that AMD is finally getting a move on but looking at that document MIOpen is a very long way off to be a slot-in replacement for CuDNN there are just so many holes it is way way further behind than MKL-DNN is for example. 

Caffe has a lot of its layer operators available both in CUDA/CuDNN versions that's why for them it probably was just 200 lines.

Worth keeping an eye on for the future but not sure if it is worth bothering at the moment.
