### ISSUE TITLE
Why does dlib's landmark detector perform so poorly on the following images? Is it expected?

### ISSUE THREAD

**Issue by yxchng** [davisking/dlib#823]
Why does dlib's landmark detector perform so poorly on the following images? 

![screenshot from 2017-09-16 13-08-51](https://user-images.githubusercontent.com/10518587/30509313-4a9af8c2-9ae0-11e7-944a-7b0eab8a24e4.png)
![screenshot from 2017-09-16 13-08-29](https://user-images.githubusercontent.com/10518587/30509314-4b456e1a-9ae0-11e7-84e0-eeca1da6c2be.png)

I am using my own face detector, so the bounding box is not from frontal face detector. However, if I use frontal face detector, the result is good. I check the coordinates, they only differ by a few pixels, which is weird. Is it that the landmark detector is highly fragile such that some pixel changes will lead to vastly different result, which mean it should always be used together with frontal_face_detector? The problem is that frontal face detector performs much worse than other deep learning based face detector, thats why I hope to use my own face detector.

**Comment by davisking** [comment]
Yes, it must always be used with the dlib face detector.  This is to be expected.  Your boxes in particular aren't even square, which is going to warp the entire algorithm since the detector it expects to be used with always outputs square boxes.  

Anyway, I just posted a 5 point face model that's trained for dlib's HOG face detector boxes and the CNN face detector in dlib which is much more accurate.  For example, the 5 point model is now the recommended model for the face recognition code: https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp.  

But if you want more than 5 points all you need to do is train a new shape predictor that will work with whatever face detector you want to use.  There is an example program that shows how to train a shape predictor.
