### ISSUE TITLE
“dlib: Killed”

### ISSUE THREAD

**Issue by magveda** [davisking/dlib#85]
I have a dataset containing 85 images with resolution of 480x640 pixels

I try to train using dlib.train_simple_object_detector, and get the error:

Training with C: 5
Training with epsilon: 0.01
Training using 2 threads.
Training with sliding window 116 pixels wide by 55 pixels tall.
Upsample images...
Upsample images...
Killed

How can I log the error? I have 2GB of RAM free available and 2 CPU cores (using virtualbox).. I am not using an XML file. I am trying to load all the images at once into memory.

You state, that "I trained a HOG face detector using about 3000 images from the labeled faces in the wild dataset and the training took only about 3 minutes". What hardware are you using?

P.S. Thank you for your great work!

**Comment by davisking** [comment]
I used a machine with 32GB of RAM and a core i7.  

Don't run it in virtualbox with a tiny amount of RAM.

**Comment by davisking** [comment]
Probably

**Comment by glenncameronjr** [comment]
Ok, thanks for the info. I'll cut it down to 1-3k images and see what happens. If it still doesn't work I have room for another 16GB of Ram.

**Comment by davisking** [comment]
You should try running imglab's --resample on your dataset.  The issue is
almost certainly that you have small objects in your images and the
internal python code upsamples them, resulting in huge images.  --resample
will resize the images and perform a more sensible cropping.  It only takes
a minute to run and you can look at the output XML file to get a sense of
what it's doing.

Make sure you grab the latest code because --resample is a very new feature
of imglab.

**Comment by glenncameronjr** [comment]
Excellent. Thanks!

**Comment by glenncameronjr** [comment]
What argument should I supply to --resample ?

**Comment by davisking** [comment]
--resample doesn't take any arguments.  Are you sure you have the newest
dlib (from github)?

**Comment by glenncameronjr** [comment]
I'm using v19.1 from this link http://dlib.net/files/dlib-19.1.tar.bz2 not from Github. I downloaded and installed a couple of hours ago. But if I run imglab -h I get this as part of the output "--resample <arg> Crop out images that are centered on each object in  the dataset. Make the crops so that the objects have <arg> pixels in them. The output is a new XML  dataset."

**Comment by davisking** [comment]
Right.  I'm saying you should get the newest copy of imglab from github :)

**Comment by glenncameronjr** [comment]
Thanks David, that did the trick! But it is labeling 0% of my images correctly. I'm going to go through all the images and make sure they are labeled correctly.

**Comment by stiv-yakovenko** [comment]
@davisking do you think it is potentially possible patch dnn_mmod_train_find_cars_ex to stream images from filesystem? I have 9Gb of mem and still its not enough to start this example.

**Comment by davisking** [comment]
Yes, certainly.  This is discussed in the documentation:
http://dlib.net/dnn_introduction2_ex.cpp.html
