### ISSUE TITLE
How can I compile dlib with Makefile

### ISSUE THREAD

**Issue by ParkSeungwon** [davisking/dlib#850]
First of all, I thank you for freely giving us this best quality libraries.
I tried to compile your GUI example code with make utility in ubuntu16.04.
g++ -std=c++14 -c gui.cpp -I..  ==> my Makefile is similar to this..

But it gives me 
"""
/usr/include/dlib/gui_core/gui_core_kernel_2.h:11:2: error: #error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
"""
this error code.. 

So I inserted #undef DLIB_NO_GUI_SUPPORT in the first line, but it still gives me the same errror.
Can't I compile it with make utility?

**Comment by ParkSeungwon** [comment]
git@github.com:ParkSeungwon/dlib.git

In case, you want to see the Makefile structure, here it is.
One example that does not use gui compiles well, while the other does not compile.

**Comment by shoeffner** [comment]
I assume your compiler does not pick up the library location for X11. While I see that your code links against X11 (`-lX11`) it might be possible you are missing `-L/usr/X11/lib` (replace `/usr/X11/lib` with wherever your X11 library files are, could also be `/opt/X11/lib` or similar).
Also I do not know exactly what `zezeon` is - and your examples don't need the mysql connector, so just using:

```
g++ -I../ -g -c -std=c++14 t.cpp -o ../obj/t.x
g++ -I../ -g -c -std=c++14 te.cpp -o ../obj/te.x
```

and in your other makefile

```
g++ -o ../t.x t.x  -lX11 -lpthread -ldlib -L/usr/X11/lib
g++ -o ../te.x te.x  -lX11 -lpthread -ldlib -L/usr/X11/lib
```

Already compiles fine for me.

If you plan to work on a bigger project I recommend you use CMake or something similar, as there linking against X11 becomes fairly trivial and you don't usually have to manually search for paths.

For your project it would be:

Create a `CMakeLists.txt` like this in your root directory:
```
cmake_minimum_required(VERSION 3.9.1)
project(test)

set(CMAKE_CXX_STANDARD 14)

find_package(X11 REQUIRED)
find_package(dlib REQUIRED)

include_directories(
    ${dlib_INCLUDE_DIRS}
    ${X11_INCLUDE_DIR}
)
link_directories(
    ${dlib_LIBRARY_DIRS}
    ${X11_LIBRARY_DIR}
)

add_executable(te.x src/te.cpp)
target_link_libraries(te.x
    ${dlib_LIBRARIES}
    ${X11_LIBRARIES}
)

add_executable(t.x src/t.cpp)
target_link_libraries(t.x
    ${dlib_LIBRARIES}
    ${X11_LIBRARIES}
)
```

Then follow these steps:

```
mkdir build
cd build
cmake ..        # Configures everything and warns if something is missing
make            # builds your project.
```
You will have your files `t.x` and `te.x` in your `build` directory.

Even if you don't settle for cmake or similar tools, I highly suggest you to make "Out of source" builds, that means to create your object files and executables in their own build directory. Will be much easier to maintain: easier to clean up and you won't accidentally commit your compiled files.

**Comment by davisking** [comment]
The problem @ParkSeungwon is having is due to installing dlib system wide with the GUI support disabled.  The only way to fix this is to recompile dlib with GUI support on.  The things @shoeffner suggest aren't going to fix that.  

I should also emphasize that you **do not need to install dlib to use it**.  In fact, I recommend that you don't install it system wide.  Instead, let cmake built it as a submodule.  Then you won't have to worry about whether or not dlib is compiled the way you need for your particular use because cmake will always build it the right way, however you might be configuring your C++ project.  Helpfully, dlib comes with a tutorial on using cmake: http://dlib.net/examples/CMakeLists.txt.html.  

You should also be using modern cmake.  This means using target properties and letting cmake deal with pulling in the appropriate dependencies.  So don't do anything with `dlib_INCLUDE_DIRS` or `dlib_LIBRARIES`.  Instead, all you need to say is 

```
target_link_libraries(your_program dlib::dlib)
```

and CMake will do the right thing.  

Anyway, look here: http://dlib.net/examples/CMakeLists.txt.html.  That tells you what to do.

**Comment by shoeffner** [comment]
Thanks, that even cleaned up my own Makefiles. I have to figure out why OpenCV does not support this so easily now though (even your example file has that problem).

I updated my answer above to point out that you have the correct answer and simplified the CMakeLists.txt accordingly. Thank you!

**Comment by davisking** [comment]
Yeah, OpenCV doesn't seem to do it yet.  Or at least the version of OpenCV in Ubuntu's package manager.  Maybe the newest version does but I haven't checked.

**Comment by davisking** [comment]
Oh and you shouldn't even need to set `CMAKE_CXX_STANDARD`.  CMake knows that needs to be set too and will do the right thing.  Although if you need it for your own code then definitely set it.

**Comment by ParkSeungwon** [comment]
Thanks shoeffner, davisking. 
I just installed it with 'sudo apt install libdlib-dev'.
I didn't touch anything else. Is ubuntu1604-repository-default  'with no gui support'?
I prefer Makefile because it is simpler. Maybe it is time to learn cmake.

**Comment by davisking** [comment]
Yes, the version of dlib in ubuntu's repository is compiled without GUI
support unfortunately.
