### ISSUE TITLE
Building with AVX/SSE on MSVC - possible bug in latest release

### ISSUE THREAD

**Issue by cysiek** [davisking/dlib#924]
Some time ago I've download and builded latest release (19.7). Today I was trying to improve the speed of my app (i'm using dlib for face detection + facial landmarks detection) and I found out that dlib was built without SSE4 and AVX. I tried to create new dlib solution using ths command line: 
`cmake -G "Visual Studio 15 2017 Win64" -DUSE_AVX_INSTRUCTIONS=ON -DUSE_SSE4_INSTRUCTIONS=ON ..\dlib-19.7`
At the end of log (console utput) I noticed this:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_AVX_INSTRUCTIONS
    USE_SSE4_INSTRUCTIONS
-- Build files have been written to: ......
```
and in the result soltuion the architecture wsn't set to AVX. In the current master(14acae3), everything is fine (same command line -> solution with architecture set to AVX == option "/arch:AVX" added). I think that the bug was already solved by this commit: https://github.com/davisking/dlib/commit/3b2d73db68d33b8d61f4b7906cfb52d90e353496#diff-543c916bb0793b3b0cd2917fad2d8314
Note the added file (set_compiler_specific_options.cmake) and line including this file added to dlib/CMakeLists.txt I think that in 19.7 - in my opinion those changes solved the problem. As far as i know, using SSE4/AVX is important for performance, so maybe it's good moment for the next release or some other solution which will make the "downloaded by default" (yes, i know about master/head, but a lot of people prefer latest release) version use SSE4&AVX ?

**Comment by davisking** [comment]
This isn't a bug in dlib.  Dlib is nearly a header only library and there isn't anything for AVX to do when "building dlib".  All the components you said you are using are defined in header files since they are templates.  

But yes, I have changed the cmake files as you noticed.  The change doesn't actually do anything substantive.  I did it mainly as part of a larger cmake cleanup and because this is a common question and it will prevent people from asking it :)

Also, what did you do with the output of that cmake build?  I'm asking because you don't need to build dlib and I moreover highly recommend that you don't.  It's much more straightforward to create projects as shown in the example cmake project: https://github.com/davisking/dlib/blob/master/examples/CMakeLists.txt

**Comment by cysiek** [comment]
Wow, i'm really surprised that i don't have to build .lib. Thanks for the information :) I thought that i need to link my app to dlib.lib file, so i added it in my cmake. I didn't even looked at the examples, because they are not working (or are disabled - nvm) on windows.

So is there any difference, whether i build my app (which uses dlib) with SSE4 or AVX? I've read here - https://www.learnopencv.com/speeding-up-dlib-facial-landmark-detector/ - that using those extensions should (significantly) increase the speed, is this true?

**Comment by davisking** [comment]
The examples aren't disabled on windows, you just need to use a compiler that supports C++11.

If you use the HOG object detector or a few other things then the code will run faster with AVX enabled.  But you have to enable AVX when _**compiling your code**_.

**Comment by cysiek** [comment]
Ok, thanks :) 
Btw - will using BLAS or LAPACK improve performance in my situation?

**Comment by davisking** [comment]
Probably not.
