### ISSUE TITLE
Mlp is not just noncopyable, but also nonmovable

### ISSUE THREAD

**Issue by facug91** [davisking/dlib#940]
Working with [mlp_kernel_c](https://github.com/davisking/dlib/blob/master/dlib/mlp/mlp_kernel_c.h) class, I needed to use it inside a vector. As it isn't copyable, I wanted to create the mlp classes directly inside the container, calling the move contructor. But as it indirectly inherits from noncopyable, that's not possible.
I think the base class, [mlp_kernel_1](https://github.com/davisking/dlib/blob/master/dlib/mlp/mlp_kernel_1.h), should not inherit from noncopyable, but redifine move constructor and move assignment, so that the copy constructor and copy assignment are not automatically generated by compiler (and it has the same behavior of non being copyable).
As I don't know if this is the expected behavior, I'm openning this issue. If it's correct, I can make a pull request.

**Comment by davisking** [comment]
You can make a PR to make it movable if you want.  However, that MLP class
is not a good classifier.  You would be much better served by something
like the `svm_c_trainer` with a radial basis function kernel.  Part of the
reason the MLP class has such an awful interface is because I've never
updated it as I don't want people to use it.  I've considered deleting it
from dlib entirely, but I don't want to break old users.  But my point is
that the MLP class is probably the worst machine learning method in dlib.
I would pick something else to use :)

**Comment by facug91** [comment]
I'm using the `svm_c_trainer` with a radial basis kernel in another part, but the thing is that I needed something much faster for a pre-classification, and mlp had been doing the job.

**Comment by davisking** [comment]
You could use krr_trainer if you want something faster.  Or you could use the the reduced2 method as shown here http://dlib.net/svm_ex.cpp.html to make the learned function faster.  Either of those is likely better than the MLP.

**Comment by davisking** [comment]
But anyway, if you want to submit a PR that makes the MLP movable that's cool with me :)

I'm just pointing out, as an aside, that dlib has better tools than the MLP :)
