### ISSUE TITLE
Issue when running setup.py with VS2017

### ISSUE THREAD

**Issue by HarrrrryLi** [davisking/dlib#972]
I try to run
`python setup.py install`
It shows

Configuring cmake ...
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  No CMAKE_C_COMPILER could be found.
CMake Error in CMakeLists.txt:
  No CMAKE_CXX_COMPILER could be found.
-- Configuring incomplete, errors occurred!

And in the log file, it's written.
The project consists entirely of configurations that require support for platforms which are not installed on this machine. The project cannot be loaded.

I installed VS 2017 on Windows 10 64 bit. So how to deal with this?

**Comment by davisking** [comment]
Something must be wrong with your visual studio install if CMake isn't finding it.  Try reinstalling visual studio, or at least opening visual studio and making sure it starts and doesn't seem broken. 

Also, you need to use visual studio 2015.  That's not why you are getting this error, but visual studio 2017 is incapable of compiling dlib since visual studio 2017 has buggy C++11 support while visual studio 2015 is less buggy with regards to C++11.
