### ISSUE TITLE
Create dlib.shape_predictor from NumPy ndarray?

### ISSUE THREAD

**Issue by manmitya** [davisking/dlib#974]
Is it possible to create in python dlib.shape_predictor object from ndarray of 5 or 68 coordinates? I saved array of face detected ractangles and landmarks as numpy-arrays for later usage. Can I create dlib.shape_predictor using this information?
I used this exaple to create numpy-array from dlib.shape_predictor:
```
def shape_to_np(shape, dtype="int"):
	# initialize the list of (x, y)-coordinates
	coords = np.zeros((68, 2), dtype=dtype) 
	# loop over the 68 facial landmarks and convert them
	# to a 2-tuple of (x, y)-coordinates
	for i in range(0, 68):
		coords[i] = (shape.part(i).x, shape.part(i).y)
	# return the list of (x, y)-coordinates
	return coords
```

**Comment by davisking** [comment]
There is a version of train_shape_predictor that takes in an array of
python objects rather than an xml file name (see the documentation
http://dlib.net/python/index.html#dlib.train_shape_predictor) if that is
what you are asking about.  But you need to train the shape predictor.  It
doesn't make sense to stuff a bunch of points and boxes into it to make
one, you need the training images and the training algorithm needs to be
executed to find the correct parameters.

**Comment by manmitya** [comment]
Thanks for the quick response! This is not exactly what I need. I was just wondering if I could restore the shape_predictor from database for its reuse in the dlib. In order not to search for the landmarks again in the image.

**Comment by davisking** [comment]
You should be able to pickle the outputs like any other python object.

**Comment by manmitya** [comment]
Ok, thank you!
