### ISSUE TITLE
'Module' object has no attribute 'cnn_face_detection_model_v1'.

### ISSUE THREAD

**Issue by SthPhoenix** [davisking/dlib#987]
Hi! I have updated to dlib 19.7 with `pip install...` but trying to run detector on CPU always caused MemoryError, so i found here a solution to setup dlib from this repository.
I have uninstalled old dlib with:
`pip uninstall dlib`
Then I have downloaded this repo and used `python setup.py install --yes USE_AVX_INSTRUCTIONS` to install it.
After those manipulations I'm getting error:
`'Module' object has no attribute 'cnn_face_detection_model_v1'.`

Also calling `dir(dlib)` shows no traces of this function/

PS: I'm trying to run code from python_examples/cnn_face_detector.py

Version: 19.7.99
From current github repo
Ubuntu 14.04.3 x64 on VMWare, no GPU, no CUDA, 16Gb RAM
Compiler: GNU 4.8.4

**Comment by davisking** [comment]
You must have an older version of dlib installed and not realize it if it's missing that function since there is no way to compile dlib without it.  So if you don't have it it's because you have an old version of dlib.

**Comment by orichardson** [comment]
I'm getting the same message. I'm using windows, and haven't managed to get Boost.Python to integrate with this project, so the most recent merge with pybind11 is the only version I have actually managed to build.  My version of dlib seems to have every other function working.

I too have tried uninstalling and reinstalling, and `dir(dlib)` does not contain anything starting with `cnn_`.

Installed with `python setup.py install`
Version 19.8.99, from git repo
CMake 3.10.1
Windows 10 x64 native, no GPU, no CUDA, 8 GB RAM
Compiler: Visual Studio 2015

**Comment by davisking** [comment]
Get the latest dlib from github (as of right now, jan 17th 2018) and try it.  Dlib is now free of boost.python, so the install should be easy.

But in any case, you must not have the version of dlib you think you have because it's impossible to compile 19.8 without that class.  There is simply no option to exclude it.  Look at `dlib.__version__` in python.  I bet it's not 19.8.

**Comment by orichardson** [comment]
I just did that, 20 minutes ago. In python, my module does not have a `__version__` field, but if I remove this version, I cannot run anything, and when I reinstall, it reappears.

I also built and ran the test suite, which completed fine:

```Testing Finished
Total number of individual testing statements executed: 469580157
All tests completed successfully```

**Comment by davisking** [comment]
No, it is not possible that cmake randomly drops files.  I also don't see how `dlib.__version__` can be missing either if you were actually using the new dlib.  The only explanation for this is that you have an old dlib.  For instance, v18.15 didn't have `dlib.__version__` nor a `dlib.cnn_face_detection_model_v1`.  So if you were using dlib v18.5 then that would explain everything.

Why don't you try running the global optimization example?  That's new in v19.8 too.  I bet that's missing as well.

**Comment by laddiexu** [comment]
I find the reason now. Because windows Anaconda has installed dlib with early version by default. It is not in pip install env but in conda install env. You can try to pip uninstall dlib. Then enter python, `import dlib`, print `dlib.__version__` to verify it. The solution is `conda uninstall dlib`, then install a newer one.
